-- *****************************************************************************
-- Améliorations des performances
-- Création d'indexes sur les clés étrangères, les dates, et les champ "enum"
-- INFO: http://archives.postgresql.org/pgsql-performance/2008-10/msg00029.php
-- INFO: il faut faire un VACUUM / REINDEX pour que les nouveaux indexes soient
--     bien pris en compte.
-- *****************************************************************************

SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;
SET search_path = public, pg_catalog;
SET default_tablespace = '';
SET default_with_oids = false;

-- -----------------------------------------------------------------------------
BEGIN;
-- -----------------------------------------------------------------------------

DROP INDEX IF EXISTS accscreaentr_microcredit_idx;
DROP INDEX IF EXISTS accscreaentr_nacre_idx;
DROP INDEX IF EXISTS actions_typeaction_id_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_bilanrecu_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_bilanretenu_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_bilanvenu_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_datebilan_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_daterdvpartenaire_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_daterecu_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_datesignature_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_ddaction_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_dfaction_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_enattente_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_integrationaction_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_mobile_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_pieceallocataire_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_presencecontrat_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_rendezvous_id_idx;
DROP INDEX IF EXISTS actionscandidats_personnes_rendezvouspartenaire_idx;
DROP INDEX IF EXISTS actionsinsertion_contratinsertion_id_idx;
DROP INDEX IF EXISTS actionsinsertion_dd_action_idx;
DROP INDEX IF EXISTS actionsinsertion_df_action_idx;
DROP INDEX IF EXISTS activites_ddact_idx;
DROP INDEX IF EXISTS activites_dfact_idx;
DROP INDEX IF EXISTS activites_personne_id_idx;
DROP INDEX IF EXISTS actsprofs_ddconvention_idx;
DROP INDEX IF EXISTS actsprofs_ddform_idx;
DROP INDEX IF EXISTS actsprofs_dfconvention_idx;
DROP INDEX IF EXISTS actsprofs_dfform_idx;
DROP INDEX IF EXISTS actsprofs_tiersprestataireapre_id_idx;
DROP INDEX IF EXISTS actsprofs_typecontratact_idx;
DROP INDEX IF EXISTS adresses_topresetr_idx;
DROP INDEX IF EXISTS adressesfoyers_adresse_id_idx;
DROP INDEX IF EXISTS adressesfoyers_dtemm_idx;
DROP INDEX IF EXISTS adressesfoyers_foyer_id_idx;
DROP INDEX IF EXISTS aidesagricoles_infoagricole_id_idx;
DROP INDEX IF EXISTS aidesapres66_autorisationvers_idx;
DROP INDEX IF EXISTS aidesapres66_datedemande_idx;
DROP INDEX IF EXISTS aidesapres66_datemontantaccorde_idx;
DROP INDEX IF EXISTS aidesapres66_datemontantpropose_idx;
DROP INDEX IF EXISTS aidesapres66_decisionapre_idx;
DROP INDEX IF EXISTS aidesapres66_versement_idx;
DROP INDEX IF EXISTS aidesapres66_virement_idx;
DROP INDEX IF EXISTS aidesdirectes_actioninsertion_id_idx;
DROP INDEX IF EXISTS aidesdirectes_date_aide_idx;
DROP INDEX IF EXISTS allocationssoutienfamilial_ddasf_idx;
DROP INDEX IF EXISTS allocationssoutienfamilial_dfasf_idx;
DROP INDEX IF EXISTS allocationssoutienfamilial_personne_id_idx;
DROP INDEX IF EXISTS allocationssoutienfamilial_topasf_idx;
DROP INDEX IF EXISTS allocationssoutienfamilial_topdemasf_idx;
DROP INDEX IF EXISTS allocationssoutienfamilial_topenfreconn_idx;
DROP INDEX IF EXISTS amenagslogts_typeaidelogement_idx;
DROP INDEX IF EXISTS amenagslogts_piecesamenagslogts_amenaglogt_id_idx;
DROP INDEX IF EXISTS amenagslogts_piecesamenagslogts_pieceamenaglogt_id_idx;
DROP INDEX IF EXISTS apres_activitebeneficiaire_idx;
DROP INDEX IF EXISTS apres_dateentreeemploi_idx;
DROP INDEX IF EXISTS apres_hasfrais_idx;
DROP INDEX IF EXISTS apres_isdecision_idx;
DROP INDEX IF EXISTS apres_justificatif_idx;
DROP INDEX IF EXISTS apres_naturelogement_idx;
DROP INDEX IF EXISTS apres_typecontrat_idx;
DROP INDEX IF EXISTS apres_typedemandeapre_idx;
DROP INDEX IF EXISTS apres_comitesapres_comite_pcd_id_idx;
DROP INDEX IF EXISTS apres_comitesapres_daterecours_idx;
DROP INDEX IF EXISTS apres_comitesapres_decisioncomite_idx;
DROP INDEX IF EXISTS apres_comitesapres_recoursapre_idx;
DROP INDEX IF EXISTS aros_acos_aco_id_idx;
DROP INDEX IF EXISTS aros_acos_aro_id_idx;
DROP INDEX IF EXISTS avispcgdroitsrsa_dossier_id_idx;
DROP INDEX IF EXISTS avispcgdroitsrsa_dtavisdestpairsa_idx;
DROP INDEX IF EXISTS avispcgpersonnes_ddexcl_idx;
DROP INDEX IF EXISTS avispcgpersonnes_dfexcl_idx;
DROP INDEX IF EXISTS avispcgpersonnes_dtevaressnonsal_idx;
DROP INDEX IF EXISTS avispcgpersonnes_dtsouressnonsal_idx;
DROP INDEX IF EXISTS avispcgpersonnes_personne_id_idx;
DROP INDEX IF EXISTS bilanparcours_accordprojet_idx;
DROP INDEX IF EXISTS bilanparcours_autreaviscommission_idx;
DROP INDEX IF EXISTS bilanparcours_aviscga_idx;
DROP INDEX IF EXISTS bilanparcours_aviscoordonnateur_idx;
DROP INDEX IF EXISTS bilanparcours_avisparcours_idx;
DROP INDEX IF EXISTS bilanparcours_changementrefeplocale_idx;
DROP INDEX IF EXISTS bilanparcours_changementrefparcours_idx;
DROP INDEX IF EXISTS bilanparcours_changementrefsansep_idx;
DROP INDEX IF EXISTS bilanparcours_choixparcours_idx;
DROP INDEX IF EXISTS bilanparcours_dateavisaudition_idx;
DROP INDEX IF EXISTS bilanparcours_dateaviscga_idx;
DROP INDEX IF EXISTS bilanparcours_dateaviscoordonnateur_idx;
DROP INDEX IF EXISTS bilanparcours_dateaviseplocale_idx;
DROP INDEX IF EXISTS bilanparcours_datebilan_idx;
DROP INDEX IF EXISTS bilanparcours_datedebreconduction_idx;
DROP INDEX IF EXISTS bilanparcours_datefinreconduction_idx;
DROP INDEX IF EXISTS bilanparcours_decisioncga_idx;
DROP INDEX IF EXISTS bilanparcours_decisioncommission_idx;
DROP INDEX IF EXISTS bilanparcours_decisioncoordonnateur_idx;
DROP INDEX IF EXISTS bilanparcours_examenaudition_idx;
DROP INDEX IF EXISTS bilanparcours_maintienorientavisep_idx;
DROP INDEX IF EXISTS bilanparcours_maintienorientparcours_idx;
DROP INDEX IF EXISTS bilanparcours_maintienorientsansep_idx;
DROP INDEX IF EXISTS bilanparcours_nvparcours_referent_id_idx;
DROP INDEX IF EXISTS bilanparcours_nvsansep_referent_id_idx;
DROP INDEX IF EXISTS bilanparcours_personne_id_idx;
DROP INDEX IF EXISTS bilanparcours_proposition_idx;
DROP INDEX IF EXISTS bilanparcours_referent_id_idx;
DROP INDEX IF EXISTS bilanparcours_rendezvous_id_idx;
DROP INDEX IF EXISTS bilanparcours_reorientation_idx;
DROP INDEX IF EXISTS bilanparcours_reorientationeplocale_idx;
DROP INDEX IF EXISTS bilanparcours_structurereferente_id_idx;
DROP INDEX IF EXISTS bilanparcours_typeeplocale_idx;
DROP INDEX IF EXISTS budgetsapres_ddexecutionbudge_idx;
DROP INDEX IF EXISTS budgetsapres_dfexecutionbudge_idx;
DROP INDEX IF EXISTS cantons_zonegeographique_id_idx;
DROP INDEX IF EXISTS comitesapres_datecomite_idx;
DROP INDEX IF EXISTS comitesapres_participantscomites_presence_idx;
/*DROP INDEX IF EXISTS conditionsactivitesprealables_ddcondactprea_idx;
DROP INDEX IF EXISTS conditionsactivitesprealables_dfcondactprea_idx;
DROP INDEX IF EXISTS conditionsactivitesprealables_personne_id_idx;
DROP INDEX IF EXISTS conditionsactivitesprealables_topcondactprea_idx;*/
DROP INDEX IF EXISTS condsadmins_avispcgdroitrsa_id_idx;
DROP INDEX IF EXISTS condsadmins_dteffaviscondadmrsa_idx;
DROP INDEX IF EXISTS connections_user_id_idx;
DROP INDEX IF EXISTS contactspartenaires_partenaire_id_idx;
DROP INDEX IF EXISTS contratsinsertion_num_contrat_idx;
DROP INDEX IF EXISTS contratsinsertion_type_demande_idx;
DROP INDEX IF EXISTS contratsinsertion_typeinsertion_idx;
DROP INDEX IF EXISTS contratsinsertion_zonegeographique_id_idx;
DROP INDEX IF EXISTS contratsinsertion_users_contratinsertion_id_idx;
DROP INDEX IF EXISTS contratsinsertion_users_user_id_idx;
DROP INDEX IF EXISTS controlesadministratifs_dtclocontro_idx;
DROP INDEX IF EXISTS controlesadministratifs_dtdeteccontro_idx;
DROP INDEX IF EXISTS controlesadministratifs_dteffcibcontro_idx;
DROP INDEX IF EXISTS creances_ddregucre_idx;
DROP INDEX IF EXISTS creances_dfregucre_idx;
DROP INDEX IF EXISTS creances_dtdercredcretrans_idx;
DROP INDEX IF EXISTS creances_dtimplcre_idx;
DROP INDEX IF EXISTS creances_foyer_id_idx;
DROP INDEX IF EXISTS creancesalimentaires_ddcrealim_idx;
DROP INDEX IF EXISTS creancesalimentaires_dfcrealim_idx;
DROP INDEX IF EXISTS creancesalimentaires_personne_id_idx;
DROP INDEX IF EXISTS cuis_adaptation_idx;
DROP INDEX IF EXISTS cuis_aiderechemploi_idx;
DROP INDEX IF EXISTS cuis_aidereprise_idx;
DROP INDEX IF EXISTS cuis_assurancechomage_idx;
DROP INDEX IF EXISTS cuis_atelierchantier_idx;
DROP INDEX IF EXISTS cuis_avenant_idx;
DROP INDEX IF EXISTS cuis_avenantcg_idx;
DROP INDEX IF EXISTS cuis_convention_idx;
DROP INDEX IF EXISTS cuis_datecontrat_idx;
DROP INDEX IF EXISTS cuis_datedebprisecharge_idx;
DROP INDEX IF EXISTS cuis_datedepot_idx;
DROP INDEX IF EXISTS cuis_dateembauche_idx;
DROP INDEX IF EXISTS cuis_datefincontrat_idx;
DROP INDEX IF EXISTS cuis_datefinprisecharge_idx;
DROP INDEX IF EXISTS cuis_datevalidationcui_idx;
DROP INDEX IF EXISTS cuis_decisioncui_idx;
DROP INDEX IF EXISTS cuis_dureebenefaide_idx;
DROP INDEX IF EXISTS cuis_dureeinscritpe_idx;
DROP INDEX IF EXISTS cuis_dureesansemploi_idx;
DROP INDEX IF EXISTS cuis_elaboprojetpro_idx;
DROP INDEX IF EXISTS cuis_evaluation_idx;
DROP INDEX IF EXISTS cuis_financementexclusif_idx;
DROP INDEX IF EXISTS cuis_formation_idx;
DROP INDEX IF EXISTS cuis_formqualif_idx;
DROP INDEX IF EXISTS cuis_handicap_idx;
DROP INDEX IF EXISTS cuis_isaas_idx;
DROP INDEX IF EXISTS cuis_isadresse2_idx;
DROP INDEX IF EXISTS cuis_isbeneficiaire_idx;
DROP INDEX IF EXISTS cuis_iscae_idx;
DROP INDEX IF EXISTS cuis_iscie_idx;
DROP INDEX IF EXISTS cuis_isinscritpe_idx;
DROP INDEX IF EXISTS cuis_isperiodepro_idx;
DROP INDEX IF EXISTS cuis_modulation_idx;
DROP INDEX IF EXISTS cuis_niveauformation_idx;
DROP INDEX IF EXISTS cuis_nouvellecompetence_idx;
DROP INDEX IF EXISTS cuis_orgapayeur_idx;
DROP INDEX IF EXISTS cuis_orgrecouvcotis_idx;
DROP INDEX IF EXISTS cuis_personne_id_idx;
DROP INDEX IF EXISTS cuis_prequalification_idx;
DROP INDEX IF EXISTS cuis_referent_id_idx;
DROP INDEX IF EXISTS cuis_remiseniveau_idx;
DROP INDEX IF EXISTS cuis_remobilisation_idx;
DROP INDEX IF EXISTS cuis_rsadeptmaj_idx;
DROP INDEX IF EXISTS cuis_secteur_idx;
DROP INDEX IF EXISTS cuis_statutemployeur_idx;
DROP INDEX IF EXISTS cuis_structurereferente_id_idx;
DROP INDEX IF EXISTS cuis_typecontrat_idx;
DROP INDEX IF EXISTS cuis_validacquis_idx;
DROP INDEX IF EXISTS decisionsparcours_created_idx;
DROP INDEX IF EXISTS decisionsparcours_maintien_idx;
DROP INDEX IF EXISTS decisionsparcours_roleparcours_idx;
DROP INDEX IF EXISTS decisionsparcours_structurereferente_id_idx;
DROP INDEX IF EXISTS derogations_avispcgpersonne_id_idx;
DROP INDEX IF EXISTS derogations_ddavisdero_idx;
DROP INDEX IF EXISTS derogations_dfavisdero_idx;
DROP INDEX IF EXISTS descriptionspdos_sensibilite_idx;
DROP INDEX IF EXISTS detailsaccosocfams_nataccosocfam_idx;
DROP INDEX IF EXISTS detailsaccosocfams_revs_nataccosocfam_idx;
DROP INDEX IF EXISTS detailsaccosocindis_nataccosocindi_idx;
DROP INDEX IF EXISTS detailsaccosocindis_revs_nataccosocindi_idx;
DROP INDEX IF EXISTS detailscalculsdroitsrsa_ddnatdro_idx;
DROP INDEX IF EXISTS detailscalculsdroitsrsa_dfnatdro_idx;
DROP INDEX IF EXISTS detailscalculsdroitsrsa_dtderrsavers_idx;
DROP INDEX IF EXISTS detailsconforts_confort_idx;
DROP INDEX IF EXISTS detailsconforts_revs_confort_idx;
DROP INDEX IF EXISTS detailsconforts_revs_dsp_rev_id_idx;
DROP INDEX IF EXISTS detailsdifdisps_difdisp_idx;
DROP INDEX IF EXISTS detailsdifdisps_revs_difdisp_idx;
DROP INDEX IF EXISTS detailsdiflogs_diflog_idx;
DROP INDEX IF EXISTS detailsdiflogs_revs_diflog_idx;
DROP INDEX IF EXISTS detailsdifsocpros_difsocpro_idx;
DROP INDEX IF EXISTS detailsdifsocpros_revs_difsocpro_idx;
DROP INDEX IF EXISTS detailsdifsocpros_revs_dsp_rev_id_idx;
DROP INDEX IF EXISTS detailsdifsocs_difsoc_idx;
DROP INDEX IF EXISTS detailsdifsocs_revs_difsoc_idx;
DROP INDEX IF EXISTS detailsdroitsrsa_ddelecal_idx;
DROP INDEX IF EXISTS detailsdroitsrsa_dfelecal_idx;
DROP INDEX IF EXISTS detailsdroitsrsa_dossier_id_idx;
DROP INDEX IF EXISTS detailsdroitsrsa_dtoridemrsa_idx;
DROP INDEX IF EXISTS detailsfreinforms_freinform_idx;
DROP INDEX IF EXISTS detailsfreinforms_revs_dsp_rev_id_idx;
DROP INDEX IF EXISTS detailsfreinforms_revs_freinform_idx;
DROP INDEX IF EXISTS detailsmoytrans_moytrans_idx;
DROP INDEX IF EXISTS detailsmoytrans_revs_dsp_rev_id_idx;
DROP INDEX IF EXISTS detailsmoytrans_revs_moytrans_idx;
DROP INDEX IF EXISTS detailsnatmobs_natmob_idx;
DROP INDEX IF EXISTS detailsnatmobs_revs_natmob_idx;
DROP INDEX IF EXISTS detailsprojpros_projpro_idx;
DROP INDEX IF EXISTS detailsprojpros_revs_dsp_rev_id_idx;
DROP INDEX IF EXISTS detailsprojpros_revs_projpro_idx;
DROP INDEX IF EXISTS detailsressourcesmensuelles_ressourcesmensuelles_detailressourcemensuelle_id_idx;
DROP INDEX IF EXISTS detailsressourcesmensuelles_ressourcesmensuelles_ressourcemensuelle_id_idx;
DROP INDEX IF EXISTS dossiers_avispcgdroitrsa_id_idx;
DROP INDEX IF EXISTS dossiers_ddarrmut_idx;
DROP INDEX IF EXISTS dossiers_dddepamut_idx;
DROP INDEX IF EXISTS dossiers_detaildroitrsa_id_idx;
DROP INDEX IF EXISTS dossiers_dtdemrmi_idx;
DROP INDEX IF EXISTS dossiers_dtdemrsa_idx;
DROP INDEX IF EXISTS dossiers_organisme_id_idx;
DROP INDEX IF EXISTS dossierscaf_ddratdos_idx;
DROP INDEX IF EXISTS dossierscaf_dfratdos_idx;
DROP INDEX IF EXISTS dossierscaf_personne_id_idx;
DROP INDEX IF EXISTS dsps_accoemploi_idx;
DROP INDEX IF EXISTS dsps_accosocfam_idx;
DROP INDEX IF EXISTS dsps_accosocindi_idx;
DROP INDEX IF EXISTS dsps_cessderact_idx;
DROP INDEX IF EXISTS dsps_concoformqualiemploi_idx;
DROP INDEX IF EXISTS dsps_demarlog_idx;
DROP INDEX IF EXISTS dsps_drorsarmianta2_idx;
DROP INDEX IF EXISTS dsps_duractdomi_idx;
DROP INDEX IF EXISTS dsps_hispro_idx;
DROP INDEX IF EXISTS dsps_inscdememploi_idx;
DROP INDEX IF EXISTS dsps_natlog_idx;
DROP INDEX IF EXISTS dsps_nivdipmaxobt_idx;
DROP INDEX IF EXISTS dsps_nivetu_idx;
DROP INDEX IF EXISTS dsps_sitpersdemrsa_idx;
DROP INDEX IF EXISTS dsps_soutdemarsoc_idx;
DROP INDEX IF EXISTS dsps_topautrpermicondu_idx;
DROP INDEX IF EXISTS dsps_topcompeextrapro_idx;
DROP INDEX IF EXISTS dsps_topcouvsoc_idx;
DROP INDEX IF EXISTS dsps_topcreareprientre_idx;
DROP INDEX IF EXISTS dsps_topdomideract_idx;
DROP INDEX IF EXISTS dsps_topdrorsarmiant_idx;
DROP INDEX IF EXISTS dsps_topengdemarechemploi_idx;
DROP INDEX IF EXISTS dsps_topisogroouenf_idx;
DROP INDEX IF EXISTS dsps_topisogrorechemploi_idx;
DROP INDEX IF EXISTS dsps_topmoyloco_idx;
DROP INDEX IF EXISTS dsps_toppermicondub_idx;
DROP INDEX IF EXISTS dsps_topprojpro_idx;
DROP INDEX IF EXISTS dsps_topqualipro_idx;
DROP INDEX IF EXISTS dsps_revs_accoemploi_idx;
DROP INDEX IF EXISTS dsps_revs_accosocfam_idx;
DROP INDEX IF EXISTS dsps_revs_accosocindi_idx;
DROP INDEX IF EXISTS dsps_revs_cessderact_idx;
DROP INDEX IF EXISTS dsps_revs_concoformqualiemploi_idx;
DROP INDEX IF EXISTS dsps_revs_created_idx;
DROP INDEX IF EXISTS dsps_revs_demarlog_idx;
DROP INDEX IF EXISTS dsps_revs_drorsarmianta2_idx;
DROP INDEX IF EXISTS dsps_revs_dsp_id_idx;
DROP INDEX IF EXISTS dsps_revs_duractdomi_idx;
DROP INDEX IF EXISTS dsps_revs_hispro_idx;
DROP INDEX IF EXISTS dsps_revs_inscdememploi_idx;
DROP INDEX IF EXISTS dsps_revs_modified_idx;
DROP INDEX IF EXISTS dsps_revs_natlog_idx;
DROP INDEX IF EXISTS dsps_revs_nivdipmaxobt_idx;
DROP INDEX IF EXISTS dsps_revs_nivetu_idx;
DROP INDEX IF EXISTS dsps_revs_sitpersdemrsa_idx;
DROP INDEX IF EXISTS dsps_revs_soutdemarsoc_idx;
DROP INDEX IF EXISTS dsps_revs_topautrpermicondu_idx;
DROP INDEX IF EXISTS dsps_revs_topcompeextrapro_idx;
DROP INDEX IF EXISTS dsps_revs_topcouvsoc_idx;
DROP INDEX IF EXISTS dsps_revs_topcreareprientre_idx;
DROP INDEX IF EXISTS dsps_revs_topdomideract_idx;
DROP INDEX IF EXISTS dsps_revs_topdrorsarmiant_idx;
DROP INDEX IF EXISTS dsps_revs_topengdemarechemploi_idx;
DROP INDEX IF EXISTS dsps_revs_topisogroouenf_idx;
DROP INDEX IF EXISTS dsps_revs_topisogrorechemploi_idx;
DROP INDEX IF EXISTS dsps_revs_topmoyloco_idx;
DROP INDEX IF EXISTS dsps_revs_toppermicondub_idx;
DROP INDEX IF EXISTS dsps_revs_topprojpro_idx;
DROP INDEX IF EXISTS dsps_revs_topqualipro_idx;
DROP INDEX IF EXISTS entretiens_nv_dsp_id_idx;
DROP INDEX IF EXISTS entretiens_referent_id_idx;
DROP INDEX IF EXISTS entretiens_rendezvous_id_idx;
DROP INDEX IF EXISTS entretiens_rendezvousprevu_idx;
DROP INDEX IF EXISTS entretiens_structurereferente_id_idx;
DROP INDEX IF EXISTS entretiens_typeentretien_idx;
DROP INDEX IF EXISTS entretiens_typerdv_id_idx;
DROP INDEX IF EXISTS entretiens_vx_dsp_id_idx;
DROP INDEX IF EXISTS evenements_dtliq_idx;
DROP INDEX IF EXISTS evenements_foyer_id_idx;
DROP INDEX IF EXISTS formspermsfimo_ddform_idx;
DROP INDEX IF EXISTS formspermsfimo_dfform_idx;
DROP INDEX IF EXISTS formspermsfimo_tiersprestataireapre_id_idx;
DROP INDEX IF EXISTS formsqualifs_ddform_idx;
DROP INDEX IF EXISTS formsqualifs_dfform_idx;
DROP INDEX IF EXISTS formsqualifs_tiersprestataireapre_id_idx;
DROP INDEX IF EXISTS foyers_ddsitfam_idx;
DROP INDEX IF EXISTS foyers_dossier_id_idx;
DROP INDEX IF EXISTS grossesses_ddgro_idx;
DROP INDEX IF EXISTS grossesses_dfgro_idx;
DROP INDEX IF EXISTS grossesses_dtdeclgro_idx;
DROP INDEX IF EXISTS grossesses_personne_id_idx;
DROP INDEX IF EXISTS groups_parent_id_idx;
DROP INDEX IF EXISTS identificationsflux_dtcreaflux_idx;
DROP INDEX IF EXISTS identificationsflux_dtref_idx;
DROP INDEX IF EXISTS informationseti_ddchiaffaeti_idx;
DROP INDEX IF EXISTS informationseti_dfchiaffaeti_idx;
DROP INDEX IF EXISTS informationseti_personne_id_idx;
DROP INDEX IF EXISTS infosagricoles_dtbenagri_idx;
DROP INDEX IF EXISTS infosagricoles_personne_id_idx;
DROP INDEX IF EXISTS infosfinancieres_ddregu_idx;
DROP INDEX IF EXISTS infosfinancieres_dossier_id_idx;
DROP INDEX IF EXISTS infosfinancieres_dttraimoucompta_idx;
DROP INDEX IF EXISTS infosfinancieres_moismoucompta_idx;
DROP INDEX IF EXISTS infospoleemploi_datecessation_idx;
DROP INDEX IF EXISTS infospoleemploi_dateinscription_idx;
DROP INDEX IF EXISTS infospoleemploi_dateradiation_idx;
DROP INDEX IF EXISTS jetons_dossier_id_idx;
DROP INDEX IF EXISTS jetons_user_id_idx;
DROP INDEX IF EXISTS liberalites_avispcgpersonne_id_idx;
DROP INDEX IF EXISTS liberalites_dtabsdeclliber_idx;
DROP INDEX IF EXISTS locsvehicinsert_pieceslocsvehicinsert_piecelocvehicinsert_id_idx;
DROP INDEX IF EXISTS memos_personne_id_idx;
DROP INDEX IF EXISTS modescontact_foyer_id_idx;
DROP INDEX IF EXISTS montantsconsommes_dateconso_idx;
DROP INDEX IF EXISTS orientations_dtrvorgorie_idx;
DROP INDEX IF EXISTS orientations_personne_id_idx;
DROP INDEX IF EXISTS orientsstructs_date_impression_relance_idx;
DROP INDEX IF EXISTS orientsstructs_daterelance_idx;
DROP INDEX IF EXISTS orientsstructs_etatorient_idx;
DROP INDEX IF EXISTS orientsstructs_referent_id_idx;
DROP INDEX IF EXISTS orientsstructs_servicesinstructeurs_orientstruct_id_idx;
DROP INDEX IF EXISTS orientsstructs_servicesinstructeurs_serviceinstructeur_id_idx;
DROP INDEX IF EXISTS paiementsfoyers_foyer_id_idx;
DROP INDEX IF EXISTS parcours_dtrvorgdeciorie_idx;
DROP INDEX IF EXISTS parcours_motimodparco_idx;
DROP INDEX IF EXISTS parcours_natparcocal_idx;
DROP INDEX IF EXISTS parcours_natparcomod_idx;
DROP INDEX IF EXISTS parcours_personne_id_idx;
DROP INDEX IF EXISTS parcours_toprefuparco_idx;
/*DROP INDEX IF EXISTS parcoursdetectes_created_idx;
DROP INDEX IF EXISTS parcoursdetectes_datetransref_idx;
DROP INDEX IF EXISTS parcoursdetectes_signale_idx;*/
DROP INDEX IF EXISTS periodesimmersion_datedebperiode_idx;
DROP INDEX IF EXISTS periodesimmersion_datefinperiode_idx;
DROP INDEX IF EXISTS periodesimmersion_datesignatureimmersion_idx;
DROP INDEX IF EXISTS periodesimmersion_objectifimmersion_idx;
DROP INDEX IF EXISTS permisb_tiersprestataireapre_id_idx;
DROP INDEX IF EXISTS personnes_dtinscpoleemploi_idx;
DROP INDEX IF EXISTS personnes_dtnati_idx;
DROP INDEX IF EXISTS personnes_referents_dddesignation_idx;
DROP INDEX IF EXISTS personnes_referents_dfdesignation_idx;
DROP INDEX IF EXISTS personnes_referents_structurereferente_id_idx;
DROP INDEX IF EXISTS personnes_upper_nom_idx;
DROP INDEX IF EXISTS personnes_upper_prenom_idx;
DROP INDEX IF EXISTS personnes_upper_nomnai_idx;
DROP INDEX IF EXISTS piecesaides66_typesaidesapres66_pieceaide66_id_idx;
DROP INDEX IF EXISTS piecesaides66_typesaidesapres66_typeaideapre66_id_idx;
DROP INDEX IF EXISTS piecescomptables66_typesaidesapres66_piececomptable66_id_idx;
DROP INDEX IF EXISTS piecescomptables66_typesaidesapres66_typeaideapre66_id_idx;
DROP INDEX IF EXISTS piecespdos_dateajout_idx;
DROP INDEX IF EXISTS precosreorients_accord_idx;
DROP INDEX IF EXISTS precosreorients_dtconcertation_idx;
DROP INDEX IF EXISTS prestsform_actioninsertion_id_idx;
DROP INDEX IF EXISTS prestsform_date_presta_idx;
DROP INDEX IF EXISTS prestsform_refpresta_id_idx;
DROP INDEX IF EXISTS propospdos_autres_idx;
DROP INDEX IF EXISTS propospdos_choixpdo_idx;
DROP INDEX IF EXISTS propospdos_datedecisionop_idx;
DROP INDEX IF EXISTS propospdos_dateecheance_idx;
DROP INDEX IF EXISTS propospdos_dateenvoiop_idx;
DROP INDEX IF EXISTS propospdos_datereceptionpdo_idx;
DROP INDEX IF EXISTS propospdos_daterevision_idx;
DROP INDEX IF EXISTS propospdos_decision_idx;
DROP INDEX IF EXISTS propospdos_decisionop_idx;
DROP INDEX IF EXISTS propospdos_etatdossierpdo_idx;
DROP INDEX IF EXISTS propospdos_iscomplet_idx;
DROP INDEX IF EXISTS propospdos_isdecisionop_idx;
DROP INDEX IF EXISTS propospdos_nonadmis_idx;
DROP INDEX IF EXISTS propospdos_originepdo_id_idx;
DROP INDEX IF EXISTS propospdos_personne_id_idx;
DROP INDEX IF EXISTS propospdos_referent_id_idx;
DROP INDEX IF EXISTS propospdos_structurereferente_id_idx;
DROP INDEX IF EXISTS propospdos_suivi_idx;
DROP INDEX IF EXISTS propospdos_typenotifpdo_id_idx;
DROP INDEX IF EXISTS propospdos_typepdo_id_idx;
DROP INDEX IF EXISTS propospdos_user_id_idx;
DROP INDEX IF EXISTS propospdos_statutsdecisionspdos_statutdecisionpdo_id_idx;
DROP INDEX IF EXISTS rattachements_dtnai_idx;
DROP INDEX IF EXISTS rattachements_personne_id_idx;
DROP INDEX IF EXISTS reducsrsa_avispcgdroitrsa_id_idx;
DROP INDEX IF EXISTS reducsrsa_ddredrsa_idx;
DROP INDEX IF EXISTS reducsrsa_dfredrsa_idx;
DROP INDEX IF EXISTS referents_structurereferente_id_idx;
DROP INDEX IF EXISTS regroupementszonesgeo_zonesgeographiques_regroupementzonegeo_id_idx;
DROP INDEX IF EXISTS regroupementszonesgeo_zonesgeographiques_zonegeographique_id_idx;
DROP INDEX IF EXISTS relancesapres_daterelance_idx;
DROP INDEX IF EXISTS relancesapres_etatdossierapre_idx;
DROP INDEX IF EXISTS rendezvous_permanence_id_idx;
DROP INDEX IF EXISTS rendezvous_personne_id_idx;
DROP INDEX IF EXISTS rendezvous_statutrdv_id_idx;
DROP INDEX IF EXISTS rendezvous_structurereferente_id_idx;
DROP INDEX IF EXISTS rendezvous_typerdv_id_idx;
DROP INDEX IF EXISTS ressources_ressourcesmensuelles_ressource_id_idx;
DROP INDEX IF EXISTS ressources_ressourcesmensuelles_ressourcemensuelle_id_idx;
DROP INDEX IF EXISTS servicesinstructeurs_numdepins_idx;
DROP INDEX IF EXISTS servicesinstructeurs_numcomins_idx;
DROP INDEX IF EXISTS servicesinstructeurs_numagrins_idx;
DROP INDEX IF EXISTS situationsdossiersrsa_dossier_id_idx;
DROP INDEX IF EXISTS structuresreferentes_apre_idx;
DROP INDEX IF EXISTS structuresreferentes_contratengagement_idx;
DROP INDEX IF EXISTS structuresreferentes_orientation_idx;
DROP INDEX IF EXISTS structuresreferentes_pdo_idx;
DROP INDEX IF EXISTS structuresreferentes_zonesgeographiques_structurereferente_id_idx;
DROP INDEX IF EXISTS suivisaidesapres_deleted_date_idx;
DROP INDEX IF EXISTS suivisaidesaprestypesaides_suiviaideapre_id_idx;
DROP INDEX IF EXISTS suivisappuisorientation_dtenrorie_idx;
DROP INDEX IF EXISTS suivisappuisorientation_dtenrparco_idx;
DROP INDEX IF EXISTS suivisappuisorientation_dtenrsocpro_idx;
DROP INDEX IF EXISTS suivisappuisorientation_personne_id_idx;
DROP INDEX IF EXISTS suivisappuisorientation_sitperssocpro_idx;
DROP INDEX IF EXISTS suivisappuisorientation_topoblsocpro_idx;
DROP INDEX IF EXISTS suivisappuisorientation_topsouhsocpro_idx;
DROP INDEX IF EXISTS suivisinstruction_date_etat_instruction_idx;
DROP INDEX IF EXISTS suivisinstruction_dossier_id_idx;
DROP INDEX IF EXISTS suivisinstruction_numdepins_idx;
DROP INDEX IF EXISTS suivisinstruction_numcomins_idx;
DROP INDEX IF EXISTS suivisinstruction_numagrins_idx;
DROP INDEX IF EXISTS tempcessations_datecessation_idx;
DROP INDEX IF EXISTS tempcessations_dtnai_idx;
DROP INDEX IF EXISTS tempinscriptions_dateinscription_idx;
DROP INDEX IF EXISTS tempinscriptions_dtnai_idx;
DROP INDEX IF EXISTS tempradiations_dateradiation_idx;
DROP INDEX IF EXISTS tempradiations_dtnai_idx;
DROP INDEX IF EXISTS titressejour_ddtitsej_idx;
DROP INDEX IF EXISTS titressejour_dftitsej_idx;
DROP INDEX IF EXISTS titressejour_dtentfra_idx;
DROP INDEX IF EXISTS titressejour_personne_id_idx;
DROP INDEX IF EXISTS totalisationsacomptes_identificationflux_id_idx;
DROP INDEX IF EXISTS traitementspdos_datedepart_idx;
DROP INDEX IF EXISTS traitementspdos_datereception_idx;
DROP INDEX IF EXISTS traitementspdos_descriptionpdo_id_idx;
DROP INDEX IF EXISTS traitementspdos_hascourrier_idx;
DROP INDEX IF EXISTS traitementspdos_hasficheanalyse_idx;
DROP INDEX IF EXISTS traitementspdos_haspiecejointe_idx;
DROP INDEX IF EXISTS traitementspdos_hasrevenu_idx;
DROP INDEX IF EXISTS traitementspdos_propopdo_id_idx;
DROP INDEX IF EXISTS traitementspdos_traitementtypepdo_id_idx;
DROP INDEX IF EXISTS transmissionsflux_identificationflux_id_idx;
DROP INDEX IF EXISTS users_date_naissance_idx;
DROP INDEX IF EXISTS users_isgestionnaire_idx;
DROP INDEX IF EXISTS users_sensibilite_idx;

-- -----------------------------------------------------------------------------

CREATE INDEX accscreaentr_microcredit_idx ON accscreaentr (microcredit);
CREATE INDEX accscreaentr_nacre_idx ON accscreaentr (nacre);
CREATE INDEX actions_typeaction_id_idx ON actions (typeaction_id);
CREATE INDEX actionscandidats_personnes_bilanrecu_idx ON actionscandidats_personnes (bilanrecu);
CREATE INDEX actionscandidats_personnes_bilanretenu_idx ON actionscandidats_personnes (bilanretenu);
CREATE INDEX actionscandidats_personnes_bilanvenu_idx ON actionscandidats_personnes (bilanvenu);
CREATE INDEX actionscandidats_personnes_datebilan_idx ON actionscandidats_personnes (datebilan);
CREATE INDEX actionscandidats_personnes_daterdvpartenaire_idx ON actionscandidats_personnes (daterdvpartenaire);
CREATE INDEX actionscandidats_personnes_daterecu_idx ON actionscandidats_personnes (daterecu);
CREATE INDEX actionscandidats_personnes_datesignature_idx ON actionscandidats_personnes (datesignature);
CREATE INDEX actionscandidats_personnes_ddaction_idx ON actionscandidats_personnes (ddaction);
CREATE INDEX actionscandidats_personnes_dfaction_idx ON actionscandidats_personnes (dfaction);
CREATE INDEX actionscandidats_personnes_enattente_idx ON actionscandidats_personnes (enattente);
CREATE INDEX actionscandidats_personnes_integrationaction_idx ON actionscandidats_personnes (integrationaction);
CREATE INDEX actionscandidats_personnes_mobile_idx ON actionscandidats_personnes (mobile);
CREATE INDEX actionscandidats_personnes_pieceallocataire_idx ON actionscandidats_personnes (pieceallocataire);
CREATE INDEX actionscandidats_personnes_presencecontrat_idx ON actionscandidats_personnes (presencecontrat);
CREATE INDEX actionscandidats_personnes_rendezvous_id_idx ON actionscandidats_personnes (rendezvous_id);
CREATE INDEX actionscandidats_personnes_rendezvouspartenaire_idx ON actionscandidats_personnes (rendezvouspartenaire);
CREATE INDEX actionsinsertion_contratinsertion_id_idx ON actionsinsertion (contratinsertion_id);
CREATE INDEX actionsinsertion_dd_action_idx ON actionsinsertion (dd_action);
CREATE INDEX actionsinsertion_df_action_idx ON actionsinsertion (df_action);
CREATE INDEX activites_ddact_idx ON activites (ddact);
CREATE INDEX activites_dfact_idx ON activites (dfact);
CREATE INDEX activites_personne_id_idx ON activites (personne_id);
CREATE INDEX actsprofs_ddconvention_idx ON actsprofs (ddconvention);
CREATE INDEX actsprofs_ddform_idx ON actsprofs (ddform);
CREATE INDEX actsprofs_dfconvention_idx ON actsprofs (dfconvention);
CREATE INDEX actsprofs_dfform_idx ON actsprofs (dfform);
CREATE INDEX actsprofs_tiersprestataireapre_id_idx ON actsprofs (tiersprestataireapre_id);
CREATE INDEX actsprofs_typecontratact_idx ON actsprofs (typecontratact);
CREATE INDEX adresses_topresetr_idx ON adresses (topresetr);
CREATE INDEX adressesfoyers_adresse_id_idx ON adressesfoyers (adresse_id);
CREATE INDEX adressesfoyers_dtemm_idx ON adressesfoyers (dtemm);
CREATE INDEX adressesfoyers_foyer_id_idx ON adressesfoyers (foyer_id);
CREATE INDEX aidesagricoles_infoagricole_id_idx ON aidesagricoles (infoagricole_id);
CREATE INDEX aidesapres66_autorisationvers_idx ON aidesapres66 (autorisationvers);
CREATE INDEX aidesapres66_datedemande_idx ON aidesapres66 (datedemande);
CREATE INDEX aidesapres66_datemontantaccorde_idx ON aidesapres66 (datemontantaccorde);
CREATE INDEX aidesapres66_datemontantpropose_idx ON aidesapres66 (datemontantpropose);
CREATE INDEX aidesapres66_decisionapre_idx ON aidesapres66 (decisionapre);
CREATE INDEX aidesapres66_versement_idx ON aidesapres66 (versement);
CREATE INDEX aidesapres66_virement_idx ON aidesapres66 (virement);
CREATE INDEX aidesdirectes_actioninsertion_id_idx ON aidesdirectes (actioninsertion_id);
CREATE INDEX aidesdirectes_date_aide_idx ON aidesdirectes (date_aide);
CREATE INDEX allocationssoutienfamilial_ddasf_idx ON allocationssoutienfamilial (ddasf);
CREATE INDEX allocationssoutienfamilial_dfasf_idx ON allocationssoutienfamilial (dfasf);
CREATE INDEX allocationssoutienfamilial_personne_id_idx ON allocationssoutienfamilial (personne_id);
CREATE INDEX allocationssoutienfamilial_topasf_idx ON allocationssoutienfamilial (topasf);
CREATE INDEX allocationssoutienfamilial_topdemasf_idx ON allocationssoutienfamilial (topdemasf);
CREATE INDEX allocationssoutienfamilial_topenfreconn_idx ON allocationssoutienfamilial (topenfreconn);
CREATE INDEX amenagslogts_typeaidelogement_idx ON amenagslogts (typeaidelogement);
CREATE INDEX amenagslogts_piecesamenagslogts_amenaglogt_id_idx ON amenagslogts_piecesamenagslogts (amenaglogt_id);
CREATE INDEX amenagslogts_piecesamenagslogts_pieceamenaglogt_id_idx ON amenagslogts_piecesamenagslogts (pieceamenaglogt_id);
CREATE INDEX apres_activitebeneficiaire_idx ON apres (activitebeneficiaire);
CREATE INDEX apres_dateentreeemploi_idx ON apres (dateentreeemploi);
CREATE INDEX apres_hasfrais_idx ON apres (hasfrais);
CREATE INDEX apres_isdecision_idx ON apres (isdecision);
CREATE INDEX apres_justificatif_idx ON apres (justificatif);
CREATE INDEX apres_naturelogement_idx ON apres (naturelogement);
CREATE INDEX apres_typecontrat_idx ON apres (typecontrat);
CREATE INDEX apres_typedemandeapre_idx ON apres (typedemandeapre);
CREATE INDEX apres_comitesapres_comite_pcd_id_idx ON apres_comitesapres (comite_pcd_id);
CREATE INDEX apres_comitesapres_daterecours_idx ON apres_comitesapres (daterecours);
CREATE INDEX apres_comitesapres_decisioncomite_idx ON apres_comitesapres (decisioncomite);
CREATE INDEX apres_comitesapres_recoursapre_idx ON apres_comitesapres (recoursapre);
CREATE INDEX aros_acos_aco_id_idx ON aros_acos (aco_id);
CREATE INDEX aros_acos_aro_id_idx ON aros_acos (aro_id);
CREATE INDEX avispcgdroitsrsa_dossier_id_idx ON avispcgdroitsrsa (dossier_id);
CREATE INDEX avispcgdroitsrsa_dtavisdestpairsa_idx ON avispcgdroitsrsa (dtavisdestpairsa);
CREATE INDEX avispcgpersonnes_ddexcl_idx ON avispcgpersonnes (ddexcl);
CREATE INDEX avispcgpersonnes_dfexcl_idx ON avispcgpersonnes (dfexcl);
CREATE INDEX avispcgpersonnes_dtevaressnonsal_idx ON avispcgpersonnes (dtevaressnonsal);
CREATE INDEX avispcgpersonnes_dtsouressnonsal_idx ON avispcgpersonnes (dtsouressnonsal);
CREATE INDEX avispcgpersonnes_personne_id_idx ON avispcgpersonnes (personne_id);
CREATE INDEX bilanparcours_accordprojet_idx ON bilanparcours (accordprojet);
CREATE INDEX bilanparcours_autreaviscommission_idx ON bilanparcours (autreaviscommission);
CREATE INDEX bilanparcours_aviscga_idx ON bilanparcours (aviscga);
CREATE INDEX bilanparcours_aviscoordonnateur_idx ON bilanparcours (aviscoordonnateur);
CREATE INDEX bilanparcours_avisparcours_idx ON bilanparcours (avisparcours);
CREATE INDEX bilanparcours_changementrefeplocale_idx ON bilanparcours (changementrefeplocale);
CREATE INDEX bilanparcours_changementrefparcours_idx ON bilanparcours (changementrefparcours);
CREATE INDEX bilanparcours_changementrefsansep_idx ON bilanparcours (changementrefsansep);
CREATE INDEX bilanparcours_choixparcours_idx ON bilanparcours (choixparcours);
CREATE INDEX bilanparcours_dateavisaudition_idx ON bilanparcours (dateavisaudition);
CREATE INDEX bilanparcours_dateaviscga_idx ON bilanparcours (dateaviscga);
CREATE INDEX bilanparcours_dateaviscoordonnateur_idx ON bilanparcours (dateaviscoordonnateur);
CREATE INDEX bilanparcours_dateaviseplocale_idx ON bilanparcours (dateaviseplocale);
CREATE INDEX bilanparcours_datebilan_idx ON bilanparcours (datebilan);
CREATE INDEX bilanparcours_datedebreconduction_idx ON bilanparcours (datedebreconduction);
CREATE INDEX bilanparcours_datefinreconduction_idx ON bilanparcours (datefinreconduction);
CREATE INDEX bilanparcours_decisioncga_idx ON bilanparcours (decisioncga);
CREATE INDEX bilanparcours_decisioncommission_idx ON bilanparcours (decisioncommission);
CREATE INDEX bilanparcours_decisioncoordonnateur_idx ON bilanparcours (decisioncoordonnateur);
CREATE INDEX bilanparcours_examenaudition_idx ON bilanparcours (examenaudition);
CREATE INDEX bilanparcours_maintienorientavisep_idx ON bilanparcours (maintienorientavisep);
CREATE INDEX bilanparcours_maintienorientparcours_idx ON bilanparcours (maintienorientparcours);
CREATE INDEX bilanparcours_maintienorientsansep_idx ON bilanparcours (maintienorientsansep);
CREATE INDEX bilanparcours_nvparcours_referent_id_idx ON bilanparcours (nvparcours_referent_id);
CREATE INDEX bilanparcours_nvsansep_referent_id_idx ON bilanparcours (nvsansep_referent_id);
CREATE INDEX bilanparcours_personne_id_idx ON bilanparcours (personne_id);
CREATE INDEX bilanparcours_proposition_idx ON bilanparcours (proposition);
CREATE INDEX bilanparcours_referent_id_idx ON bilanparcours (referent_id);
CREATE INDEX bilanparcours_rendezvous_id_idx ON bilanparcours (rendezvous_id);
CREATE INDEX bilanparcours_reorientation_idx ON bilanparcours (reorientation);
CREATE INDEX bilanparcours_reorientationeplocale_idx ON bilanparcours (reorientationeplocale);
CREATE INDEX bilanparcours_structurereferente_id_idx ON bilanparcours (structurereferente_id);
CREATE INDEX bilanparcours_typeeplocale_idx ON bilanparcours (typeeplocale);
CREATE INDEX budgetsapres_ddexecutionbudge_idx ON budgetsapres (ddexecutionbudge);
CREATE INDEX budgetsapres_dfexecutionbudge_idx ON budgetsapres (dfexecutionbudge);
CREATE INDEX cantons_zonegeographique_id_idx ON cantons (zonegeographique_id);
CREATE INDEX comitesapres_datecomite_idx ON comitesapres (datecomite);
CREATE INDEX comitesapres_participantscomites_presence_idx ON comitesapres_participantscomites (presence);
/*CREATE INDEX conditionsactivitesprealables_ddcondactprea_idx ON conditionsactivitesprealables (ddcondactprea);
CREATE INDEX conditionsactivitesprealables_dfcondactprea_idx ON conditionsactivitesprealables (dfcondactprea);
CREATE INDEX conditionsactivitesprealables_personne_id_idx ON conditionsactivitesprealables (personne_id);
CREATE INDEX conditionsactivitesprealables_topcondactprea_idx ON conditionsactivitesprealables (topcondactprea);*/
CREATE INDEX condsadmins_avispcgdroitrsa_id_idx ON condsadmins (avispcgdroitrsa_id);
CREATE INDEX condsadmins_dteffaviscondadmrsa_idx ON condsadmins (dteffaviscondadmrsa);
CREATE INDEX connections_user_id_idx ON connections (user_id);
CREATE INDEX contactspartenaires_partenaire_id_idx ON contactspartenaires (partenaire_id);
CREATE INDEX contratsinsertion_num_contrat_idx ON contratsinsertion (num_contrat);
CREATE INDEX contratsinsertion_type_demande_idx ON contratsinsertion (type_demande);
CREATE INDEX contratsinsertion_typeinsertion_idx ON contratsinsertion (typeinsertion);
CREATE INDEX contratsinsertion_zonegeographique_id_idx ON contratsinsertion (zonegeographique_id);
CREATE INDEX contratsinsertion_users_contratinsertion_id_idx ON contratsinsertion_users (contratinsertion_id);
CREATE INDEX contratsinsertion_users_user_id_idx ON contratsinsertion_users (user_id);
CREATE INDEX controlesadministratifs_dtclocontro_idx ON controlesadministratifs (dtclocontro);
CREATE INDEX controlesadministratifs_dtdeteccontro_idx ON controlesadministratifs (dtdeteccontro);
CREATE INDEX controlesadministratifs_dteffcibcontro_idx ON controlesadministratifs (dteffcibcontro);
CREATE INDEX creances_ddregucre_idx ON creances (ddregucre);
CREATE INDEX creances_dfregucre_idx ON creances (dfregucre);
CREATE INDEX creances_dtdercredcretrans_idx ON creances (dtdercredcretrans);
CREATE INDEX creances_dtimplcre_idx ON creances (dtimplcre);
CREATE INDEX creances_foyer_id_idx ON creances (foyer_id);
CREATE INDEX creancesalimentaires_ddcrealim_idx ON creancesalimentaires (ddcrealim);
CREATE INDEX creancesalimentaires_dfcrealim_idx ON creancesalimentaires (dfcrealim);
CREATE INDEX creancesalimentaires_personne_id_idx ON creancesalimentaires (personne_id);
CREATE INDEX cuis_adaptation_idx ON cuis (adaptation);
CREATE INDEX cuis_aiderechemploi_idx ON cuis (aiderechemploi);
CREATE INDEX cuis_aidereprise_idx ON cuis (aidereprise);
CREATE INDEX cuis_assurancechomage_idx ON cuis (assurancechomage);
CREATE INDEX cuis_atelierchantier_idx ON cuis (atelierchantier);
CREATE INDEX cuis_avenant_idx ON cuis (avenant);
CREATE INDEX cuis_avenantcg_idx ON cuis (avenantcg);
CREATE INDEX cuis_convention_idx ON cuis (convention);
CREATE INDEX cuis_datecontrat_idx ON cuis (datecontrat);
CREATE INDEX cuis_datedebprisecharge_idx ON cuis (datedebprisecharge);
CREATE INDEX cuis_datedepot_idx ON cuis (datedepot);
CREATE INDEX cuis_dateembauche_idx ON cuis (dateembauche);
CREATE INDEX cuis_datefincontrat_idx ON cuis (datefincontrat);
CREATE INDEX cuis_datefinprisecharge_idx ON cuis (datefinprisecharge);
CREATE INDEX cuis_datevalidationcui_idx ON cuis (datevalidationcui);
CREATE INDEX cuis_decisioncui_idx ON cuis (decisioncui);
CREATE INDEX cuis_dureebenefaide_idx ON cuis (dureebenefaide);
CREATE INDEX cuis_dureeinscritpe_idx ON cuis (dureeinscritpe);
CREATE INDEX cuis_dureesansemploi_idx ON cuis (dureesansemploi);
CREATE INDEX cuis_elaboprojetpro_idx ON cuis (elaboprojetpro);
CREATE INDEX cuis_evaluation_idx ON cuis (evaluation);
CREATE INDEX cuis_financementexclusif_idx ON cuis (financementexclusif);
CREATE INDEX cuis_formation_idx ON cuis (formation);
CREATE INDEX cuis_formqualif_idx ON cuis (formqualif);
CREATE INDEX cuis_handicap_idx ON cuis (handicap);
CREATE INDEX cuis_isaas_idx ON cuis (isaas);
CREATE INDEX cuis_isadresse2_idx ON cuis (isadresse2);
CREATE INDEX cuis_isbeneficiaire_idx ON cuis (isbeneficiaire);
CREATE INDEX cuis_iscae_idx ON cuis (iscae);
CREATE INDEX cuis_iscie_idx ON cuis (iscie);
CREATE INDEX cuis_isinscritpe_idx ON cuis (isinscritpe);
CREATE INDEX cuis_isperiodepro_idx ON cuis (isperiodepro);
CREATE INDEX cuis_modulation_idx ON cuis (modulation);
CREATE INDEX cuis_niveauformation_idx ON cuis (niveauformation);
CREATE INDEX cuis_nouvellecompetence_idx ON cuis (nouvellecompetence);
CREATE INDEX cuis_orgapayeur_idx ON cuis (orgapayeur);
CREATE INDEX cuis_orgrecouvcotis_idx ON cuis (orgrecouvcotis);
CREATE INDEX cuis_personne_id_idx ON cuis (personne_id);
CREATE INDEX cuis_prequalification_idx ON cuis (prequalification);
CREATE INDEX cuis_referent_id_idx ON cuis (referent_id);
CREATE INDEX cuis_remiseniveau_idx ON cuis (remiseniveau);
CREATE INDEX cuis_remobilisation_idx ON cuis (remobilisation);
CREATE INDEX cuis_rsadeptmaj_idx ON cuis (rsadeptmaj);
CREATE INDEX cuis_secteur_idx ON cuis (secteur);
CREATE INDEX cuis_statutemployeur_idx ON cuis (statutemployeur);
CREATE INDEX cuis_structurereferente_id_idx ON cuis (structurereferente_id);
CREATE INDEX cuis_typecontrat_idx ON cuis (typecontrat);
CREATE INDEX cuis_validacquis_idx ON cuis (validacquis);
CREATE INDEX decisionsparcours_created_idx ON decisionsparcours (created);
CREATE INDEX decisionsparcours_maintien_idx ON decisionsparcours (maintien);
CREATE INDEX decisionsparcours_roleparcours_idx ON decisionsparcours (roleparcours);
CREATE INDEX decisionsparcours_structurereferente_id_idx ON decisionsparcours (structurereferente_id);
CREATE INDEX derogations_avispcgpersonne_id_idx ON derogations (avispcgpersonne_id);
CREATE INDEX derogations_ddavisdero_idx ON derogations (ddavisdero);
CREATE INDEX derogations_dfavisdero_idx ON derogations (dfavisdero);
CREATE INDEX descriptionspdos_sensibilite_idx ON descriptionspdos (sensibilite);
CREATE INDEX detailsaccosocfams_nataccosocfam_idx ON detailsaccosocfams (nataccosocfam);
CREATE INDEX detailsaccosocfams_revs_nataccosocfam_idx ON detailsaccosocfams_revs (nataccosocfam);
CREATE INDEX detailsaccosocindis_nataccosocindi_idx ON detailsaccosocindis (nataccosocindi);
CREATE INDEX detailsaccosocindis_revs_nataccosocindi_idx ON detailsaccosocindis_revs (nataccosocindi);
CREATE INDEX detailscalculsdroitsrsa_ddnatdro_idx ON detailscalculsdroitsrsa (ddnatdro);
CREATE INDEX detailscalculsdroitsrsa_dfnatdro_idx ON detailscalculsdroitsrsa (dfnatdro);
CREATE INDEX detailscalculsdroitsrsa_dtderrsavers_idx ON detailscalculsdroitsrsa (dtderrsavers);
CREATE INDEX detailsconforts_confort_idx ON detailsconforts (confort);
CREATE INDEX detailsconforts_revs_confort_idx ON detailsconforts_revs (confort);
CREATE INDEX detailsconforts_revs_dsp_rev_id_idx ON detailsconforts_revs (dsp_rev_id);
CREATE INDEX detailsdifdisps_difdisp_idx ON detailsdifdisps (difdisp);
CREATE INDEX detailsdifdisps_revs_difdisp_idx ON detailsdifdisps_revs (difdisp);
CREATE INDEX detailsdiflogs_diflog_idx ON detailsdiflogs (diflog);
CREATE INDEX detailsdiflogs_revs_diflog_idx ON detailsdiflogs_revs (diflog);
CREATE INDEX detailsdifsocpros_difsocpro_idx ON detailsdifsocpros (difsocpro);
CREATE INDEX detailsdifsocpros_revs_difsocpro_idx ON detailsdifsocpros_revs (difsocpro);
CREATE INDEX detailsdifsocpros_revs_dsp_rev_id_idx ON detailsdifsocpros_revs (dsp_rev_id);
CREATE INDEX detailsdifsocs_difsoc_idx ON detailsdifsocs (difsoc);
CREATE INDEX detailsdifsocs_revs_difsoc_idx ON detailsdifsocs_revs (difsoc);
CREATE INDEX detailsdroitsrsa_ddelecal_idx ON detailsdroitsrsa (ddelecal);
CREATE INDEX detailsdroitsrsa_dfelecal_idx ON detailsdroitsrsa (dfelecal);
CREATE INDEX detailsdroitsrsa_dossier_id_idx ON detailsdroitsrsa (dossier_id);
CREATE INDEX detailsdroitsrsa_dtoridemrsa_idx ON detailsdroitsrsa (dtoridemrsa);
CREATE INDEX detailsfreinforms_freinform_idx ON detailsfreinforms (freinform);
CREATE INDEX detailsfreinforms_revs_dsp_rev_id_idx ON detailsfreinforms_revs (dsp_rev_id);
CREATE INDEX detailsfreinforms_revs_freinform_idx ON detailsfreinforms_revs (freinform);
CREATE INDEX detailsmoytrans_moytrans_idx ON detailsmoytrans (moytrans);
CREATE INDEX detailsmoytrans_revs_dsp_rev_id_idx ON detailsmoytrans_revs (dsp_rev_id);
CREATE INDEX detailsmoytrans_revs_moytrans_idx ON detailsmoytrans_revs (moytrans);
CREATE INDEX detailsnatmobs_natmob_idx ON detailsnatmobs (natmob);
CREATE INDEX detailsnatmobs_revs_natmob_idx ON detailsnatmobs_revs (natmob);
CREATE INDEX detailsprojpros_projpro_idx ON detailsprojpros (projpro);
CREATE INDEX detailsprojpros_revs_dsp_rev_id_idx ON detailsprojpros_revs (dsp_rev_id);
CREATE INDEX detailsprojpros_revs_projpro_idx ON detailsprojpros_revs (projpro);
CREATE INDEX detailsressourcesmensuelles_ressourcesmensuelles_detailressourcemensuelle_id_idx ON detailsressourcesmensuelles_ressourcesmensuelles (detailressourcemensuelle_id);
CREATE INDEX detailsressourcesmensuelles_ressourcesmensuelles_ressourcemensuelle_id_idx ON detailsressourcesmensuelles_ressourcesmensuelles (ressourcemensuelle_id);
CREATE INDEX dossiers_avispcgdroitrsa_id_idx ON dossiers (avispcgdroitrsa_id);
CREATE INDEX dossiers_ddarrmut_idx ON dossiers (ddarrmut);
CREATE INDEX dossiers_dddepamut_idx ON dossiers (dddepamut);
CREATE INDEX dossiers_detaildroitrsa_id_idx ON dossiers (detaildroitrsa_id);
CREATE INDEX dossiers_dtdemrmi_idx ON dossiers (dtdemrmi);
CREATE INDEX dossiers_dtdemrsa_idx ON dossiers (dtdemrsa);
CREATE INDEX dossiers_organisme_id_idx ON dossiers (organisme_id);
CREATE INDEX dossierscaf_ddratdos_idx ON dossierscaf (ddratdos);
CREATE INDEX dossierscaf_dfratdos_idx ON dossierscaf (dfratdos);
CREATE INDEX dossierscaf_personne_id_idx ON dossierscaf (personne_id);
CREATE INDEX dsps_accoemploi_idx ON dsps (accoemploi);
CREATE INDEX dsps_accosocfam_idx ON dsps (accosocfam);
CREATE INDEX dsps_accosocindi_idx ON dsps (accosocindi);
CREATE INDEX dsps_cessderact_idx ON dsps (cessderact);
CREATE INDEX dsps_concoformqualiemploi_idx ON dsps (concoformqualiemploi);
CREATE INDEX dsps_demarlog_idx ON dsps (demarlog);
CREATE INDEX dsps_drorsarmianta2_idx ON dsps (drorsarmianta2);
CREATE INDEX dsps_duractdomi_idx ON dsps (duractdomi);
CREATE INDEX dsps_hispro_idx ON dsps (hispro);
CREATE INDEX dsps_inscdememploi_idx ON dsps (inscdememploi);
CREATE INDEX dsps_natlog_idx ON dsps (natlog);
CREATE INDEX dsps_nivdipmaxobt_idx ON dsps (nivdipmaxobt);
CREATE INDEX dsps_nivetu_idx ON dsps (nivetu);
CREATE INDEX dsps_sitpersdemrsa_idx ON dsps (sitpersdemrsa);
CREATE INDEX dsps_soutdemarsoc_idx ON dsps (soutdemarsoc);
CREATE INDEX dsps_topautrpermicondu_idx ON dsps (topautrpermicondu);
CREATE INDEX dsps_topcompeextrapro_idx ON dsps (topcompeextrapro);
CREATE INDEX dsps_topcouvsoc_idx ON dsps (topcouvsoc);
CREATE INDEX dsps_topcreareprientre_idx ON dsps (topcreareprientre);
CREATE INDEX dsps_topdomideract_idx ON dsps (topdomideract);
CREATE INDEX dsps_topdrorsarmiant_idx ON dsps (topdrorsarmiant);
CREATE INDEX dsps_topengdemarechemploi_idx ON dsps (topengdemarechemploi);
CREATE INDEX dsps_topisogroouenf_idx ON dsps (topisogroouenf);
CREATE INDEX dsps_topisogrorechemploi_idx ON dsps (topisogrorechemploi);
CREATE INDEX dsps_topmoyloco_idx ON dsps (topmoyloco);
CREATE INDEX dsps_toppermicondub_idx ON dsps (toppermicondub);
CREATE INDEX dsps_topprojpro_idx ON dsps (topprojpro);
CREATE INDEX dsps_topqualipro_idx ON dsps (topqualipro);
CREATE INDEX dsps_revs_accoemploi_idx ON dsps_revs (accoemploi);
CREATE INDEX dsps_revs_accosocfam_idx ON dsps_revs (accosocfam);
CREATE INDEX dsps_revs_accosocindi_idx ON dsps_revs (accosocindi);
CREATE INDEX dsps_revs_cessderact_idx ON dsps_revs (cessderact);
CREATE INDEX dsps_revs_concoformqualiemploi_idx ON dsps_revs (concoformqualiemploi);
CREATE INDEX dsps_revs_created_idx ON dsps_revs (created);
CREATE INDEX dsps_revs_demarlog_idx ON dsps_revs (demarlog);
CREATE INDEX dsps_revs_drorsarmianta2_idx ON dsps_revs (drorsarmianta2);
CREATE INDEX dsps_revs_dsp_id_idx ON dsps_revs (dsp_id);
CREATE INDEX dsps_revs_duractdomi_idx ON dsps_revs (duractdomi);
CREATE INDEX dsps_revs_hispro_idx ON dsps_revs (hispro);
CREATE INDEX dsps_revs_inscdememploi_idx ON dsps_revs (inscdememploi);
CREATE INDEX dsps_revs_modified_idx ON dsps_revs (modified);
CREATE INDEX dsps_revs_natlog_idx ON dsps_revs (natlog);
CREATE INDEX dsps_revs_nivdipmaxobt_idx ON dsps_revs (nivdipmaxobt);
CREATE INDEX dsps_revs_nivetu_idx ON dsps_revs (nivetu);
CREATE INDEX dsps_revs_sitpersdemrsa_idx ON dsps_revs (sitpersdemrsa);
CREATE INDEX dsps_revs_soutdemarsoc_idx ON dsps_revs (soutdemarsoc);
CREATE INDEX dsps_revs_topautrpermicondu_idx ON dsps_revs (topautrpermicondu);
CREATE INDEX dsps_revs_topcompeextrapro_idx ON dsps_revs (topcompeextrapro);
CREATE INDEX dsps_revs_topcouvsoc_idx ON dsps_revs (topcouvsoc);
CREATE INDEX dsps_revs_topcreareprientre_idx ON dsps_revs (topcreareprientre);
CREATE INDEX dsps_revs_topdomideract_idx ON dsps_revs (topdomideract);
CREATE INDEX dsps_revs_topdrorsarmiant_idx ON dsps_revs (topdrorsarmiant);
CREATE INDEX dsps_revs_topengdemarechemploi_idx ON dsps_revs (topengdemarechemploi);
CREATE INDEX dsps_revs_topisogroouenf_idx ON dsps_revs (topisogroouenf);
CREATE INDEX dsps_revs_topisogrorechemploi_idx ON dsps_revs (topisogrorechemploi);
CREATE INDEX dsps_revs_topmoyloco_idx ON dsps_revs (topmoyloco);
CREATE INDEX dsps_revs_toppermicondub_idx ON dsps_revs (toppermicondub);
CREATE INDEX dsps_revs_topprojpro_idx ON dsps_revs (topprojpro);
CREATE INDEX dsps_revs_topqualipro_idx ON dsps_revs (topqualipro);
CREATE INDEX entretiens_nv_dsp_id_idx ON entretiens (nv_dsp_id);
CREATE INDEX entretiens_referent_id_idx ON entretiens (referent_id);
CREATE INDEX entretiens_rendezvous_id_idx ON entretiens (rendezvous_id);
CREATE INDEX entretiens_rendezvousprevu_idx ON entretiens (rendezvousprevu);
CREATE INDEX entretiens_structurereferente_id_idx ON entretiens (structurereferente_id);
CREATE INDEX entretiens_typeentretien_idx ON entretiens (typeentretien);
CREATE INDEX entretiens_typerdv_id_idx ON entretiens (typerdv_id);
CREATE INDEX entretiens_vx_dsp_id_idx ON entretiens (vx_dsp_id);
CREATE INDEX evenements_dtliq_idx ON evenements (dtliq);
CREATE INDEX evenements_foyer_id_idx ON evenements (foyer_id);
CREATE INDEX formspermsfimo_ddform_idx ON formspermsfimo (ddform);
CREATE INDEX formspermsfimo_dfform_idx ON formspermsfimo (dfform);
CREATE INDEX formspermsfimo_tiersprestataireapre_id_idx ON formspermsfimo (tiersprestataireapre_id);
CREATE INDEX formsqualifs_ddform_idx ON formsqualifs (ddform);
CREATE INDEX formsqualifs_dfform_idx ON formsqualifs (dfform);
CREATE INDEX formsqualifs_tiersprestataireapre_id_idx ON formsqualifs (tiersprestataireapre_id);
CREATE INDEX foyers_ddsitfam_idx ON foyers (ddsitfam);
CREATE INDEX foyers_dossier_id_idx ON foyers (dossier_id);
CREATE INDEX grossesses_ddgro_idx ON grossesses (ddgro);
CREATE INDEX grossesses_dfgro_idx ON grossesses (dfgro);
CREATE INDEX grossesses_dtdeclgro_idx ON grossesses (dtdeclgro);
CREATE INDEX grossesses_personne_id_idx ON grossesses (personne_id);
CREATE INDEX groups_parent_id_idx ON groups (parent_id);
CREATE INDEX identificationsflux_dtcreaflux_idx ON identificationsflux (dtcreaflux);
CREATE INDEX identificationsflux_dtref_idx ON identificationsflux (dtref);
CREATE INDEX informationseti_ddchiaffaeti_idx ON informationseti (ddchiaffaeti);
CREATE INDEX informationseti_dfchiaffaeti_idx ON informationseti (dfchiaffaeti);
CREATE INDEX informationseti_personne_id_idx ON informationseti (personne_id);
CREATE INDEX infosagricoles_dtbenagri_idx ON infosagricoles (dtbenagri);
CREATE INDEX infosagricoles_personne_id_idx ON infosagricoles (personne_id);
CREATE INDEX infosfinancieres_ddregu_idx ON infosfinancieres (ddregu);
CREATE INDEX infosfinancieres_dossier_id_idx ON infosfinancieres (dossier_id);
CREATE INDEX infosfinancieres_dttraimoucompta_idx ON infosfinancieres (dttraimoucompta);
CREATE INDEX infosfinancieres_moismoucompta_idx ON infosfinancieres (moismoucompta);
CREATE INDEX infospoleemploi_datecessation_idx ON infospoleemploi (datecessation);
CREATE INDEX infospoleemploi_dateinscription_idx ON infospoleemploi (dateinscription);
CREATE INDEX infospoleemploi_dateradiation_idx ON infospoleemploi (dateradiation);
CREATE INDEX jetons_dossier_id_idx ON jetons (dossier_id);
CREATE INDEX jetons_user_id_idx ON jetons (user_id);
CREATE INDEX liberalites_avispcgpersonne_id_idx ON liberalites (avispcgpersonne_id);
CREATE INDEX liberalites_dtabsdeclliber_idx ON liberalites (dtabsdeclliber);
CREATE INDEX locsvehicinsert_pieceslocsvehicinsert_piecelocvehicinsert_id_idx ON locsvehicinsert_pieceslocsvehicinsert (piecelocvehicinsert_id);
CREATE INDEX memos_personne_id_idx ON memos (personne_id);
CREATE INDEX modescontact_foyer_id_idx ON modescontact (foyer_id);
CREATE INDEX montantsconsommes_dateconso_idx ON montantsconsommes (dateconso);
CREATE INDEX orientations_dtrvorgorie_idx ON orientations (dtrvorgorie);
CREATE INDEX orientations_personne_id_idx ON orientations (personne_id);
CREATE INDEX orientsstructs_date_impression_relance_idx ON orientsstructs (date_impression_relance);
CREATE INDEX orientsstructs_daterelance_idx ON orientsstructs (daterelance);
CREATE INDEX orientsstructs_etatorient_idx ON orientsstructs (etatorient);
CREATE INDEX orientsstructs_referent_id_idx ON orientsstructs (referent_id);
CREATE INDEX orientsstructs_servicesinstructeurs_orientstruct_id_idx ON orientsstructs_servicesinstructeurs (orientstruct_id);
CREATE INDEX orientsstructs_servicesinstructeurs_serviceinstructeur_id_idx ON orientsstructs_servicesinstructeurs (serviceinstructeur_id);
CREATE INDEX paiementsfoyers_foyer_id_idx ON paiementsfoyers (foyer_id);
CREATE INDEX parcours_dtrvorgdeciorie_idx ON parcours (dtrvorgdeciorie);
CREATE INDEX parcours_motimodparco_idx ON parcours (motimodparco);
CREATE INDEX parcours_natparcocal_idx ON parcours (natparcocal);
CREATE INDEX parcours_natparcomod_idx ON parcours (natparcomod);
CREATE INDEX parcours_personne_id_idx ON parcours (personne_id);
CREATE INDEX parcours_toprefuparco_idx ON parcours (toprefuparco);
/*CREATE INDEX parcoursdetectes_created_idx ON parcoursdetectes (created);
CREATE INDEX parcoursdetectes_datetransref_idx ON parcoursdetectes (datetransref);
CREATE INDEX parcoursdetectes_signale_idx ON parcoursdetectes (signale);*/
CREATE INDEX periodesimmersion_datedebperiode_idx ON periodesimmersion (datedebperiode);
CREATE INDEX periodesimmersion_datefinperiode_idx ON periodesimmersion (datefinperiode);
CREATE INDEX periodesimmersion_datesignatureimmersion_idx ON periodesimmersion (datesignatureimmersion);
CREATE INDEX periodesimmersion_objectifimmersion_idx ON periodesimmersion (objectifimmersion);
CREATE INDEX permisb_tiersprestataireapre_id_idx ON permisb (tiersprestataireapre_id);
CREATE INDEX personnes_dtinscpoleemploi_idx ON personnes (dtinscpoleemploi);
CREATE INDEX personnes_dtnati_idx ON personnes (dtnati);
CREATE INDEX personnes_referents_dddesignation_idx ON personnes_referents (dddesignation);
CREATE INDEX personnes_referents_dfdesignation_idx ON personnes_referents (dfdesignation);
CREATE INDEX personnes_referents_structurereferente_id_idx ON personnes_referents (structurereferente_id);
CREATE INDEX personnes_upper_nom_idx ON personnes USING btree (upper(nom::text) varchar_pattern_ops);
CREATE INDEX personnes_upper_prenom_idx ON personnes USING btree (UPPER(prenom) varchar_pattern_ops);
CREATE INDEX personnes_upper_nomnai_idx ON personnes USING btree (UPPER(nomnai) varchar_pattern_ops);
CREATE INDEX piecesaides66_typesaidesapres66_pieceaide66_id_idx ON piecesaides66_typesaidesapres66 (pieceaide66_id);
CREATE INDEX piecesaides66_typesaidesapres66_typeaideapre66_id_idx ON piecesaides66_typesaidesapres66 (typeaideapre66_id);
CREATE INDEX piecescomptables66_typesaidesapres66_piececomptable66_id_idx ON piecescomptables66_typesaidesapres66 (piececomptable66_id);
CREATE INDEX piecescomptables66_typesaidesapres66_typeaideapre66_id_idx ON piecescomptables66_typesaidesapres66 (typeaideapre66_id);
CREATE INDEX piecespdos_dateajout_idx ON piecespdos (dateajout);
CREATE INDEX precosreorients_accord_idx ON precosreorients (accord);
CREATE INDEX precosreorients_dtconcertation_idx ON precosreorients (dtconcertation);
CREATE INDEX prestsform_actioninsertion_id_idx ON prestsform (actioninsertion_id);
CREATE INDEX prestsform_date_presta_idx ON prestsform (date_presta);
CREATE INDEX prestsform_refpresta_id_idx ON prestsform (refpresta_id);
CREATE INDEX propospdos_autres_idx ON propospdos (autres);
CREATE INDEX propospdos_choixpdo_idx ON propospdos (choixpdo);
CREATE INDEX propospdos_datedecisionop_idx ON propospdos (datedecisionop);
CREATE INDEX propospdos_dateecheance_idx ON propospdos (dateecheance);
CREATE INDEX propospdos_dateenvoiop_idx ON propospdos (dateenvoiop);
CREATE INDEX propospdos_datereceptionpdo_idx ON propospdos (datereceptionpdo);
CREATE INDEX propospdos_daterevision_idx ON propospdos (daterevision);
CREATE INDEX propospdos_decision_idx ON propospdos (decision);
CREATE INDEX propospdos_decisionop_idx ON propospdos (decisionop);
CREATE INDEX propospdos_etatdossierpdo_idx ON propospdos (etatdossierpdo);
CREATE INDEX propospdos_iscomplet_idx ON propospdos (iscomplet);
CREATE INDEX propospdos_isdecisionop_idx ON propospdos (isdecisionop);
CREATE INDEX propospdos_nonadmis_idx ON propospdos (nonadmis);
CREATE INDEX propospdos_originepdo_id_idx ON propospdos (originepdo_id);
CREATE INDEX propospdos_personne_id_idx ON propospdos (personne_id);
CREATE INDEX propospdos_referent_id_idx ON propospdos (referent_id);
CREATE INDEX propospdos_structurereferente_id_idx ON propospdos (structurereferente_id);
CREATE INDEX propospdos_suivi_idx ON propospdos (suivi);
CREATE INDEX propospdos_typenotifpdo_id_idx ON propospdos (typenotifpdo_id);
CREATE INDEX propospdos_typepdo_id_idx ON propospdos (typepdo_id);
CREATE INDEX propospdos_user_id_idx ON propospdos (user_id);
CREATE INDEX propospdos_statutsdecisionspdos_statutdecisionpdo_id_idx ON propospdos_statutsdecisionspdos (statutdecisionpdo_id);
CREATE INDEX rattachements_dtnai_idx ON rattachements (dtnai);
CREATE INDEX rattachements_personne_id_idx ON rattachements (personne_id);
CREATE INDEX reducsrsa_avispcgdroitrsa_id_idx ON reducsrsa (avispcgdroitrsa_id);
CREATE INDEX reducsrsa_ddredrsa_idx ON reducsrsa (ddredrsa);
CREATE INDEX reducsrsa_dfredrsa_idx ON reducsrsa (dfredrsa);
CREATE INDEX referents_structurereferente_id_idx ON referents (structurereferente_id);
CREATE INDEX regroupementszonesgeo_zonesgeographiques_regroupementzonegeo_id_idx ON regroupementszonesgeo_zonesgeographiques (regroupementzonegeo_id);
CREATE INDEX regroupementszonesgeo_zonesgeographiques_zonegeographique_id_idx ON regroupementszonesgeo_zonesgeographiques (zonegeographique_id);
CREATE INDEX relancesapres_daterelance_idx ON relancesapres (daterelance);
CREATE INDEX relancesapres_etatdossierapre_idx ON relancesapres (etatdossierapre);
CREATE INDEX rendezvous_permanence_id_idx ON rendezvous (permanence_id);
CREATE INDEX rendezvous_personne_id_idx ON rendezvous (personne_id);
CREATE INDEX rendezvous_statutrdv_id_idx ON rendezvous (statutrdv_id);
CREATE INDEX rendezvous_structurereferente_id_idx ON rendezvous (structurereferente_id);
CREATE INDEX rendezvous_typerdv_id_idx ON rendezvous (typerdv_id);
CREATE INDEX ressources_ressourcesmensuelles_ressource_id_idx ON ressources_ressourcesmensuelles (ressource_id);
CREATE INDEX ressources_ressourcesmensuelles_ressourcemensuelle_id_idx ON ressources_ressourcesmensuelles (ressourcemensuelle_id);
CREATE INDEX servicesinstructeurs_numdepins_idx ON servicesinstructeurs (numdepins);
CREATE INDEX servicesinstructeurs_numcomins_idx ON servicesinstructeurs (numcomins);
CREATE INDEX servicesinstructeurs_numagrins_idx ON servicesinstructeurs (numagrins);
CREATE INDEX situationsdossiersrsa_dossier_id_idx ON situationsdossiersrsa (dossier_id);
CREATE INDEX structuresreferentes_apre_idx ON structuresreferentes (apre);
CREATE INDEX structuresreferentes_contratengagement_idx ON structuresreferentes (contratengagement);
CREATE INDEX structuresreferentes_orientation_idx ON structuresreferentes (orientation);
CREATE INDEX structuresreferentes_pdo_idx ON structuresreferentes (pdo);
CREATE INDEX structuresreferentes_zonesgeographiques_structurereferente_id_idx ON structuresreferentes_zonesgeographiques (structurereferente_id);
CREATE INDEX suivisaidesapres_deleted_date_idx ON suivisaidesapres (deleted_date);
CREATE INDEX suivisaidesaprestypesaides_suiviaideapre_id_idx ON suivisaidesaprestypesaides (suiviaideapre_id);
CREATE INDEX suivisappuisorientation_dtenrorie_idx ON suivisappuisorientation (dtenrorie);
CREATE INDEX suivisappuisorientation_dtenrparco_idx ON suivisappuisorientation (dtenrparco);
CREATE INDEX suivisappuisorientation_dtenrsocpro_idx ON suivisappuisorientation (dtenrsocpro);
CREATE INDEX suivisappuisorientation_personne_id_idx ON suivisappuisorientation (personne_id);
CREATE INDEX suivisappuisorientation_sitperssocpro_idx ON suivisappuisorientation (sitperssocpro);
CREATE INDEX suivisappuisorientation_topoblsocpro_idx ON suivisappuisorientation (topoblsocpro);
CREATE INDEX suivisappuisorientation_topsouhsocpro_idx ON suivisappuisorientation (topsouhsocpro);
CREATE INDEX suivisinstruction_date_etat_instruction_idx ON suivisinstruction (date_etat_instruction);
CREATE INDEX suivisinstruction_dossier_id_idx ON suivisinstruction (dossier_id);
CREATE INDEX suivisinstruction_numdepins_idx ON suivisinstruction (numdepins);
CREATE INDEX suivisinstruction_numcomins_idx ON suivisinstruction (numcomins);
CREATE INDEX suivisinstruction_numagrins_idx ON suivisinstruction (numagrins);
CREATE INDEX tempcessations_datecessation_idx ON tempcessations (datecessation);
CREATE INDEX tempcessations_dtnai_idx ON tempcessations (dtnai);
CREATE INDEX tempinscriptions_dateinscription_idx ON tempinscriptions (dateinscription);
CREATE INDEX tempinscriptions_dtnai_idx ON tempinscriptions (dtnai);
CREATE INDEX tempradiations_dateradiation_idx ON tempradiations (dateradiation);
CREATE INDEX tempradiations_dtnai_idx ON tempradiations (dtnai);
CREATE INDEX titressejour_ddtitsej_idx ON titressejour (ddtitsej);
CREATE INDEX titressejour_dftitsej_idx ON titressejour (dftitsej);
CREATE INDEX titressejour_dtentfra_idx ON titressejour (dtentfra);
CREATE INDEX titressejour_personne_id_idx ON titressejour (personne_id);
CREATE INDEX totalisationsacomptes_identificationflux_id_idx ON totalisationsacomptes (identificationflux_id);
CREATE INDEX traitementspdos_datedepart_idx ON traitementspdos (datedepart);
CREATE INDEX traitementspdos_datereception_idx ON traitementspdos (datereception);
CREATE INDEX traitementspdos_descriptionpdo_id_idx ON traitementspdos (descriptionpdo_id);
CREATE INDEX traitementspdos_hascourrier_idx ON traitementspdos (hascourrier);
CREATE INDEX traitementspdos_hasficheanalyse_idx ON traitementspdos (hasficheanalyse);
CREATE INDEX traitementspdos_haspiecejointe_idx ON traitementspdos (haspiecejointe);
CREATE INDEX traitementspdos_hasrevenu_idx ON traitementspdos (hasrevenu);
CREATE INDEX traitementspdos_propopdo_id_idx ON traitementspdos (propopdo_id);
CREATE INDEX traitementspdos_traitementtypepdo_id_idx ON traitementspdos (traitementtypepdo_id);
CREATE INDEX transmissionsflux_identificationflux_id_idx ON transmissionsflux (identificationflux_id);
CREATE INDEX users_date_naissance_idx ON users (date_naissance);
CREATE INDEX users_isgestionnaire_idx ON users (isgestionnaire);
CREATE INDEX users_sensibilite_idx ON users (sensibilite);

-- -----------------------------------------------------------------------------
-- 20110214 - eps-indexes-current.sql
-- -----------------------------------------------------------------------------

DROP INDEX IF EXISTS bilansparcours66_accompagnement_idx;
DROP INDEX IF EXISTS bilansparcours66_accordprojet_idx;
DROP INDEX IF EXISTS bilansparcours66_changementrefeplocale_idx;
DROP INDEX IF EXISTS bilansparcours66_changementrefparcours_idx;
DROP INDEX IF EXISTS bilansparcours66_changementrefsansep_idx;
DROP INDEX IF EXISTS bilansparcours66_changereferent_idx;
DROP INDEX IF EXISTS bilansparcours66_choixparcours_idx;
DROP INDEX IF EXISTS bilansparcours66_datebilan_idx;
DROP INDEX IF EXISTS bilansparcours66_ddreconductoncontrat_idx;
DROP INDEX IF EXISTS bilansparcours66_decisioncga_idx;
DROP INDEX IF EXISTS bilansparcours66_decisioncommission_idx;
DROP INDEX IF EXISTS bilansparcours66_decisioncoordonnateur_idx;
DROP INDEX IF EXISTS bilansparcours66_dfreconductoncontrat_idx;
DROP INDEX IF EXISTS bilansparcours66_examenaudition_idx;
DROP INDEX IF EXISTS bilansparcours66_maintienorientation_idx;
DROP INDEX IF EXISTS bilansparcours66_maintienorientavisep_idx;
DROP INDEX IF EXISTS bilansparcours66_maintienorientparcours_idx;
DROP INDEX IF EXISTS bilansparcours66_maintienorientsansep_idx;
DROP INDEX IF EXISTS bilansparcours66_presenceallocataire_idx;
DROP INDEX IF EXISTS bilansparcours66_reorientation_idx;
DROP INDEX IF EXISTS bilansparcours66_reorientationeplocale_idx;
DROP INDEX IF EXISTS bilansparcours66_saisineepparcours_idx;
DROP INDEX IF EXISTS bilansparcours66_typeeplocale_idx;
DROP INDEX IF EXISTS bilansparcours66_typeformulaire_idx;
DROP INDEX IF EXISTS decisionsdefautsinsertionseps66_structurereferente_id_idx;
DROP INDEX IF EXISTS decisionsdefautsinsertionseps66_typeorient_id_idx;
DROP INDEX IF EXISTS decisionsnonrespectssanctionseps93_decision_idx;
DROP INDEX IF EXISTS decisionsnonrespectssanctionseps93_etape_idx;
DROP INDEX IF EXISTS descriptionspdos_dateactive_idx;
DROP INDEX IF EXISTS descriptionspdos_declencheep_idx;
DROP INDEX IF EXISTS dossierseps_seanceep_id_idx;
DROP INDEX IF EXISTS dossierseps_themeep_idx;
DROP INDEX IF EXISTS eps_defautinsertionep66_idx;
DROP INDEX IF EXISTS eps_nonrespectsanctionep93_idx;
DROP INDEX IF EXISTS eps_saisineepbilanparcours66_idx;
DROP INDEX IF EXISTS eps_saisineepdpdo66_idx;
DROP INDEX IF EXISTS eps_saisineepreorientsr93_idx;
DROP INDEX IF EXISTS membreseps_qual_idx;
DROP INDEX IF EXISTS membreseps_suppleant_id_idx;
DROP INDEX IF EXISTS membreseps_seanceseps_membreep_id_idx;
DROP INDEX IF EXISTS membreseps_seanceseps_presence_idx;
DROP INDEX IF EXISTS membreseps_seanceseps_reponse_idx;
DROP INDEX IF EXISTS membreseps_seanceseps_suppleant_idx;
DROP INDEX IF EXISTS membreseps_seanceseps_suppleant_id_idx;
DROP INDEX IF EXISTS nonrespectssanctionseps93_decision_idx;
DROP INDEX IF EXISTS nonrespectssanctionseps93_origine_idx;
DROP INDEX IF EXISTS nonrespectssanctionseps93_sortienvcontrat_idx;
DROP INDEX IF EXISTS nvsepdspdos66_datedecisionpdo_idx;
DROP INDEX IF EXISTS nvsepdspdos66_etape_idx;
DROP INDEX IF EXISTS nvsepdspdos66_nonadmis_idx;
DROP INDEX IF EXISTS nvsrsepsreorient66_decision_idx;
DROP INDEX IF EXISTS nvsrsepsreorient66_etape_idx;
DROP INDEX IF EXISTS nvsrsepsreorientsrs93_decision_idx;
DROP INDEX IF EXISTS nvsrsepsreorientsrs93_etape_idx;
DROP INDEX IF EXISTS propospdos_orgpayeur_idx;
DROP INDEX IF EXISTS relancesnonrespectssanctionseps93_dateimpression_idx;
DROP INDEX IF EXISTS relancesnonrespectssanctionseps93_daterelance_idx;
DROP INDEX IF EXISTS saisinesepsreorientsrs93_accordaccueil_idx;
DROP INDEX IF EXISTS saisinesepsreorientsrs93_accordallocataire_idx;
DROP INDEX IF EXISTS saisinesepsreorientsrs93_urgent_idx;
DROP INDEX IF EXISTS seanceseps_finalisee_idx;
DROP INDEX IF EXISTS traitementspdos_dateecheance_idx;
DROP INDEX IF EXISTS traitementspdos_daterevision_idx;

-- -----------------------------------------------------------------------------

CREATE INDEX bilansparcours66_accompagnement_idx ON bilansparcours66 (accompagnement);
CREATE INDEX bilansparcours66_accordprojet_idx ON bilansparcours66 (accordprojet);
CREATE INDEX bilansparcours66_changementrefeplocale_idx ON bilansparcours66 (changementrefeplocale);
CREATE INDEX bilansparcours66_changementrefparcours_idx ON bilansparcours66 (changementrefparcours);
CREATE INDEX bilansparcours66_changementrefsansep_idx ON bilansparcours66 (changementrefsansep);
CREATE INDEX bilansparcours66_changereferent_idx ON bilansparcours66 (changereferent);
CREATE INDEX bilansparcours66_choixparcours_idx ON bilansparcours66 (choixparcours);
CREATE INDEX bilansparcours66_datebilan_idx ON bilansparcours66 (datebilan);
CREATE INDEX bilansparcours66_ddreconductoncontrat_idx ON bilansparcours66 (ddreconductoncontrat);
CREATE INDEX bilansparcours66_decisioncga_idx ON bilansparcours66 (decisioncga);
CREATE INDEX bilansparcours66_decisioncommission_idx ON bilansparcours66 (decisioncommission);
CREATE INDEX bilansparcours66_decisioncoordonnateur_idx ON bilansparcours66 (decisioncoordonnateur);
CREATE INDEX bilansparcours66_dfreconductoncontrat_idx ON bilansparcours66 (dfreconductoncontrat);
CREATE INDEX bilansparcours66_examenaudition_idx ON bilansparcours66 (examenaudition);
CREATE INDEX bilansparcours66_maintienorientation_idx ON bilansparcours66 (maintienorientation);
CREATE INDEX bilansparcours66_maintienorientavisep_idx ON bilansparcours66 (maintienorientavisep);
CREATE INDEX bilansparcours66_maintienorientparcours_idx ON bilansparcours66 (maintienorientparcours);
CREATE INDEX bilansparcours66_maintienorientsansep_idx ON bilansparcours66 (maintienorientsansep);
CREATE INDEX bilansparcours66_presenceallocataire_idx ON bilansparcours66 (presenceallocataire);
CREATE INDEX bilansparcours66_reorientation_idx ON bilansparcours66 (reorientation);
CREATE INDEX bilansparcours66_reorientationeplocale_idx ON bilansparcours66 (reorientationeplocale);
CREATE INDEX bilansparcours66_saisineepparcours_idx ON bilansparcours66 (saisineepparcours);
CREATE INDEX bilansparcours66_typeeplocale_idx ON bilansparcours66 (typeeplocale);
CREATE INDEX bilansparcours66_typeformulaire_idx ON bilansparcours66 (typeformulaire);
CREATE INDEX decisionsdefautsinsertionseps66_structurereferente_id_idx ON decisionsdefautsinsertionseps66 (structurereferente_id);
CREATE INDEX decisionsdefautsinsertionseps66_typeorient_id_idx ON decisionsdefautsinsertionseps66 (typeorient_id);
CREATE INDEX decisionsnonrespectssanctionseps93_decision_idx ON decisionsnonrespectssanctionseps93 (decision);
CREATE INDEX decisionsnonrespectssanctionseps93_etape_idx ON decisionsnonrespectssanctionseps93 (etape);
CREATE INDEX descriptionspdos_dateactive_idx ON descriptionspdos (dateactive);
CREATE INDEX descriptionspdos_declencheep_idx ON descriptionspdos (declencheep);
CREATE INDEX dossierseps_seanceep_id_idx ON dossierseps (seanceep_id);
CREATE INDEX dossierseps_themeep_idx ON dossierseps (themeep);
CREATE INDEX eps_defautinsertionep66_idx ON eps (defautinsertionep66);
CREATE INDEX eps_nonrespectsanctionep93_idx ON eps (nonrespectsanctionep93);
CREATE INDEX eps_saisineepbilanparcours66_idx ON eps (saisineepbilanparcours66);
CREATE INDEX eps_saisineepdpdo66_idx ON eps (saisineepdpdo66);
CREATE INDEX eps_saisineepreorientsr93_idx ON eps (saisineepreorientsr93);
CREATE INDEX membreseps_qual_idx ON membreseps (qual);
CREATE INDEX membreseps_suppleant_id_idx ON membreseps (suppleant_id);
CREATE INDEX membreseps_seanceseps_membreep_id_idx ON membreseps_seanceseps (membreep_id);
CREATE INDEX membreseps_seanceseps_presence_idx ON membreseps_seanceseps (presence);
CREATE INDEX membreseps_seanceseps_reponse_idx ON membreseps_seanceseps (reponse);
CREATE INDEX membreseps_seanceseps_suppleant_idx ON membreseps_seanceseps (suppleant);
CREATE INDEX membreseps_seanceseps_suppleant_id_idx ON membreseps_seanceseps (suppleant_id);
CREATE INDEX nonrespectssanctionseps93_decision_idx ON nonrespectssanctionseps93 (decision);
CREATE INDEX nonrespectssanctionseps93_origine_idx ON nonrespectssanctionseps93 (origine);
CREATE INDEX nonrespectssanctionseps93_sortienvcontrat_idx ON nonrespectssanctionseps93 (sortienvcontrat);
CREATE INDEX nvsepdspdos66_datedecisionpdo_idx ON nvsepdspdos66 (datedecisionpdo);
CREATE INDEX nvsepdspdos66_etape_idx ON nvsepdspdos66 (etape);
CREATE INDEX nvsepdspdos66_nonadmis_idx ON nvsepdspdos66 (nonadmis);
CREATE INDEX nvsrsepsreorient66_decision_idx ON nvsrsepsreorient66 (decision);
CREATE INDEX nvsrsepsreorient66_etape_idx ON nvsrsepsreorient66 (etape);
CREATE INDEX nvsrsepsreorientsrs93_decision_idx ON nvsrsepsreorientsrs93 (decision);
CREATE INDEX nvsrsepsreorientsrs93_etape_idx ON nvsrsepsreorientsrs93 (etape);
CREATE INDEX propospdos_orgpayeur_idx ON propospdos (orgpayeur);
CREATE INDEX relancesnonrespectssanctionseps93_dateimpression_idx ON relancesnonrespectssanctionseps93 (dateimpression);
CREATE INDEX relancesnonrespectssanctionseps93_daterelance_idx ON relancesnonrespectssanctionseps93 (daterelance);
CREATE INDEX saisinesepsreorientsrs93_accordaccueil_idx ON saisinesepsreorientsrs93 (accordaccueil);
CREATE INDEX saisinesepsreorientsrs93_accordallocataire_idx ON saisinesepsreorientsrs93 (accordallocataire);
CREATE INDEX saisinesepsreorientsrs93_urgent_idx ON saisinesepsreorientsrs93 (urgent);
CREATE INDEX seanceseps_finalisee_idx ON seanceseps (finalisee);
CREATE INDEX traitementspdos_dateecheance_idx ON traitementspdos (dateecheance);
CREATE INDEX traitementspdos_daterevision_idx ON traitementspdos (daterevision);

-- -----------------------------------------------------------------------------
COMMIT;
-- -----------------------------------------------------------------------------