<?php
	/**
	 * Code source de la classe Fluxcnaf.
	 *
	 * PHP 5.3
	 *
	 * @package Fluxcnaf.Model
	 * @license CeCiLL V2 (http://www.cecill.info/licences/Licence_CeCILL_V2-fr.html)
	 */

	/**
	 * La classe Fluxcnaf ...
	 *
	 * @package Fluxcnaf.Model
	 */
	class Fluxcnaf extends AppModel
	{
		/**
		 * Nom du modèle.
		 *
		 * @var string
		 */
		public $name = 'Fluxcnaf';

		/**
		 * Ce modèle ne possède pas de table liée
		 *
		 * @var mixed
		 */
		public $useTable = false;

		/**
		 * Tables propres à web-rsa ayant des champs portant le même nom que des
		 * tables de flux CNAF.
		 *
		 * @var array
		 */
		public $tablesNonCaf = array(
			'cers93', 'situationsallocataires', 'composfoyerscers93', 'contactspartenaires',
			'histoaprecomplementaires', 'informationspe', 'membreseps', 'participantscomites',
			'personnescuis', 'referents', 'suivisaidesapres', 'users', 'historiquesdroits',
			'contratsinsertion', 'adressescuis', 'adressesprestatairesfps93', 'cantons',
			'immersionscuis66', 'orientations' /*pour adresses*/, 'partenaires', 'permanences',
			'prestataireshorspdifps93', 'tiersprestatairesapres',
			'detailsaccosocfams_revs', 'detailsaccosocindis_revs', 'detailsdifdisps_revs', 'detailsdiflogs_revs',
			'detailsdifsocs_revs', 'detailsnatmobs_revs', 'dsps_revs',
			'questionnairesd1pdvs93', 'apres', 'partenairescuis66'
		);

		public $flux = array(
			// TODO: vérifier si TOPVALIEC est personnes.topvalec
			'Bénéficiaire VRSB0801-Cristal V4200' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
					'DTREF',
				),
				'/InfosFoyerRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE'
				),
				'/InfosFoyerRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosFoyerRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA'
				),
				'/InfosFoyerRSA/IdentificationRSA/DemandeRMI/DateDemandeRMI' => array(
					'DTDEMRMI',
				),
				'/InfosFoyerRSA/IdentificationRSA/DemandeRMI/NumeroInstructionRMI' => array(
					'NUMDEPINSRMI',
					'TYPEINSRMI',
					'NUMCOMINSRMI',
					'NUMAGRINSRMI',
					'NUMDOSINSRMI',
					'NUMCLI',
				),
				'/InfosFoyerRSA/IdentificationRSA/OrganismeCedant' => array(
					'FONORGCEDMUT',
					'NUMORGCEDMUT',
					'MATRICULEORGCEDMUT',
					'DDARRMUT',
				),
				'/InfosFoyerRSA/IdentificationRSA/OrganismePrenant' => array(
					'FONORGPRENMUT',
					'NUMORGPRENMUT',
					'DDDEPAMUT',
				),
				'/InfosFoyerRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
					'PRENOM2',
					'PRENOM3',
					'NOMCOMNAI',
					'DTNAI',
					'RGNAI',
					'TYPEDTNAI',
					'NIR',
					'TOPVALIEC',
					'SEXE',
				),
				'/InfosFoyerRSA/Personne/DossierCAF' => array(
					'TOPRESPDOS',
					'DDRATDOS',
					'DFRATDOS',
					'NUMDEMRSAPRECE',
				),
				'/InfosFoyerRSA/Personne/Prestations' => array(
					'NATPREST',
					'ROLEPERS',
					'TOPCHAPERS',
				),
				'/InfosFoyerRSA/Personne/Rattachement' => array(
					'NOMNAI',
					'PRENOM',
					'DTNAI',
					'NIR',
					'TYPEPAR',
				),
				'/InfosFoyerRSA/Personne/DossierPoleEmploi' => array(
					'IDASSEDIC',
				),
				'/InfosFoyerRSA/Personne/Ressources/GeneraliteRessourcesTrimestre' => array(
					'TOPRESSNUL',
					'DDRESS',
					'DFRESS',
				),
				'/InfosFoyerRSA/Personne/Ressources/RessourcesMensuelles/GeneraliteRessourcesMensuelles' => array(
					'MOISRESS',
					'NBHEUMENTRA',
				),
				'/InfosFoyerRSA/Personne/Ressources/RessourcesMensuelles/DetailRessourcesMensuelles' => array(
					'NATRESS',
					'MTNATRESSMEN',
					'ABANEU',
				),
				'/InfosFoyerRSA/Personne/MontantCalculDroitRSAPersonne' => array(
					'TOPPERSDRODEVORSA',
					'TOPPERSENTDRODEVORSA',
					'MTPERSRESSMENRSA',
					'MTPERSABANEURSA',
				),
				'/InfosFoyerRSA/Personne/Activite' => array(
					'REG',
					'ACT',
					'DDACT',
					'DFACT',
					'NATCONTRTRA',
					'TOPCONDADMETI',
				),
				'/InfosFoyerRSA/Personne/PensionAlimentaire/Asf' => array(
					'SITASF',
					'PARASSOASF',
					'DDASF',
					'DFASF',
				),
				'/InfosFoyerRSA/Personne/PensionAlimentaire/CreanceAlimentaire' => array(
					'ETATCREALIM',
					'DDCREALIM',
					'DFCREALIM',
					'ORIOBLALIM',
					'MOTIDISCREALIM',
					'COMMCREALIM',
					'MTSANCREALIM',
				),
				'/InfosFoyerRSA/Personne/Grossesse' => array(
					'DDGRO',
					'DFGRO',
					'DTDECLGRO',
					'NATFINGRO',
				),
				'/InfosFoyerRSA/Personne/InformationsAgricoles' => array(
					'MTBENAGRI',
					'REGFISAGRI',
					'DTBENAGRI',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ConditionETI' => array(
					'AVISEVARESSNONSAL',
					'DTSOURESSNONSAL',
					'DTEVARESSNONSAL',
					'MTEVARESSNONSAL',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/Dérogation' => array(
					'TYPEDERO',
					'AVISDERO',
					'DDAVISDERO',
					'DFAVISDERO',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ExclueRSA' => array(
					'EXCL',
					'DDEXCL',
					'DFEXCL',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/Liberalite' => array(
					'MTLIBERNONDECL',
					'DTABSDECLLIBER',
				),
				'/InfosFoyerRSA/Personne/AvisCGSSDOMPersonne' => array(
					'JUSACTDOM',
					'RESUJUSACTDOM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/SituationFamille' => array(
					'SITFAM',
					'DDSITFAM',
					'REGAGRIFAM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse/TroncCommunAdresse' => array(
					'RGADR',
					'DTEMM',
					'PAYS',
					'TYPEADR',
					'ETATADR',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse/AdresseDetailleeFrance' => array(
					'COMPLIDEADR',
					'COMPLADR',
					'NUMVOIE',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'NUMCOM',
					'NUMCOMPTT',
					'CODEPOS',
					'NOMCOM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse/AdresseHorsFrance' => array(
					'LIBLIG2ADR',
					'LIBLIG3ADR',
					'LIBLIG4ADR',
					'LIBLIG5ADR',
					'LIBLIG6ADR',
					'LIBLIG7ADR',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/EtatDossierRSA' => array(
					'ETATDOSRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/Refus' => array(
					'DTREFURSA',
					'MOTIREFURSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/SuspensionDroit' => array(
					'MOTISUSDRORSA',
					'DDSUSDRORSA',
					'NATGROUPFSUS',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/SuspensionVersement' => array(
					'MOTISUSVERSRSA',
					'DDSUSVERSRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/FinDroit' => array(
					'MOTICLORSA',
					'DTCLORSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/FinDroitMoisAnterieur' => array(
					'MOTICLORSA',
					'DTCLORSA',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/TroncCommunDroitRSA' => array(
					'TOPSANSDOMFIXE',
					'NBENFAUTCHA',
					'ORIDEMRSA',
					'DTORIDEMRSA',
					'TOPFOYDRODEVORSA',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/SpecificiteDOM' => array(
					'SURFAGRIDOM',
					'DDSURFAGRIDOM',
					'SURFAGRIDOMPLA',
					'NBTOTAIDEFAMSURFDOM',
					'NBTOTPERSMAJOSURFDOM',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/MontantsCalculDroitRSA' => array(
					'DDELECAL',
					'DFELECAL',
					'MTREVMINIGARARSA',
					'MTPENTRSA',
					'MTLOCALRSA',
					'MTREVGARARSA',
					'MTPFRSA',
					'MTALRSA',
					'MTRESSMENRSA',
					'MTSANOBLALIMRSA',
					'MTREDHOSRSA',
					'MTREDCGRSA',
					'MTCUMINTEGRSA',
					'MTABANEURSA',
					'MTTOTDRORSA',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'MTRSAVERS',
					'DTDERRSAVERS',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/AvisPCGDroitRSA/ConditionAdministrative' => array(
					'AVISCONDADMRSA',
					'MOTICONDADMRSA',
					'COMM1CONDADMRSA',
					'COMM2CONDADMRSA',
					'DTEFFAVISCONDADMRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/AvisPCGDroitRSA/ReductionRSA' => array(
					'MTREDRSA',
					'DDREDRSA',
					'DFREDRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/AvisPCGDroitRSA/PaiementTiers' => array(
					'AVISDESTPAIRSA',
					'DTAVISDESTPAIRSA',
					'NOMTIE',
					'TYPEPERSTIE',
				),
				'/InfosFoyerRSA/Evenement' => array(
					'DTLIQ',
					'HEULIQ',
					'FG',
				),
				'/InfosFoyerRSA/Controle/ControleAdministratif/IdentificationCibleControleAdministratif' => array(
					'DTEFFCIBCONTRO',
					'CIBCONTRO',
					'CIBCONTROMSA',
				),
				'/InfosFoyerRSA/Controle/ControleAdministratif/IdentificationControleAdministratif' => array(
					'DTDETECCONTRO',
					'DTCLOCONTRO',
				),
				'/InfosFoyerRSA/Controle/ControleAdministratif/ModaliteControleAdministratif' => array(
					'LIBCIBCONTRO',
					'FAMCIBCONTRO',
					'NATCIBCONTRO',
					'COMMACONTRO',
					'TYPECONTRO',
				),
				'/InfosFoyerRSA/Controle/ControleAdministratif/ResultatControleAdministratif' => array(
					'TYPEIMPACCONTRO',
					'MTINDURSACGCONTRO',
					'MTRAPRSACGCONTRO',
				),
				'/InfosFoyerRSA/Anomalie' => array(
					'LIBANO'
				),
				'/TransmissionFlux' => array(
					'NBTOTDOSRSATRANSM',
					'NBTOTDOSRSATRANSMANO',
				),
			),
			'Instruction VIRS0901-V15.00' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
				),
				'/InfoDemandeRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE',
					'STATUDEMRSA',
				),
				'/InfoDemandeRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfoDemandeRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA',
				),
				'/InfoDemandeRSA/IdentificationRSA/OrganismeCedant' => array(
					'FONORGCEDMUT',
					'NUMORGCEDMUT',
					'MATRICULEORGCEDMUT',
					'CODEPOSANCHAB',
				),
				'/InfoDemandeRSA/IdentificationRSA/SuiviInstruction' => array(
					'SUIIRSA',
					'NOMINS',
					'PRENOMINS',
					'NUMDEPINS',
					'TYPESERINS',
					'NUMCOMINS',
					'NUMAGRINS',
				),
				'/InfoDemandeRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
					'PRENOM2',
					'PRENOM3',
					'NOMCOMNAI',
					'DTNAI',
					'RGNAI',
					'TYPEDTNAI',
					'NIR',
					'SEXE',
				),
				'/InfoDemandeRSA/Personne/Nationalite' => array(
					'NATI',
					'DTNATI',
				),
				'/InfoDemandeRSA/Personne/DossierCAF' => array(
					'DDRATDOS',
					'DFRATDOS',
				),
				'/InfoDemandeRSA/Personne/Prestations' => array(
					'NATPREST',
					'ROLEPERS',
				),
				'/InfoDemandeRSA/Personne/Rattachement' => array(
					'NOMNAI',
					'PRENOM',
					'DTNAI',
					'NIR',
					'TYPEPAR',
				),
				'/InfoDemandeRSA/Personne/TitreSejour' => array(
					'DTENTFRA',
					'NATTITSEJ',
					'MENTTITSEJ',
					'DDTITSEJ',
					'DFTITSEJ',
					'NUMTITSEJ',
					'NUMDUPTITSEJ',
				),
				'/InfoDemandeRSA/Personne/Ressources/GeneraliteRessourcesTrimestre' => array(
					'TOPRESSNUL',
					'DDRESS',
					'DFRESS',
				),
				'/InfoDemandeRSA/Personne/Ressources/RessourcesMensuelles/GeneraliteRessourcesMensuelles' => array(
					'MOISRESS',
					'NBHEUMENTRA',
				),
				'/InfoDemandeRSA/Personne/Ressources/RessourcesMensuelles/DetailRessourcesMensuelles' => array(
					'NATRESS',
					'MTNATRESSMEN',
					'DFPERCRESS',
					'TOPREVSUBSRESS',
				),
				'/InfoDemandeRSA/Personne/Activite' => array(
					'REG',
					'ACT',
					'PAYSACT',
					'DDACT',
					'DFACT',
					'NATCONTRTRA',
					'HAUREMUSMIC',
				),
				'/InfoDemandeRSA/Personne/PensionAlimentaire/Asf' => array(
					'SITASF',
					'TOPASF',
					'TOPDEMASF',
					'TOPENFRECONN',
				),
				'/InfoDemandeRSA/Personne/PensionAlimentaire/CreanceAlimentaire' => array(
					'TOPDEMDISPROCCREALIM',
					'ENGPROCCREALIM',
					'ETATCREALIM',
					'DDCREALIM',
					'ORIOBLALIM',
					'MOTIDISCREALIM',
					'COMMCREALIM',
					'MTSANCREALIM',
					'VERSPA',
					'TOPJUGPA',
				),
				'/InfoDemandeRSA/Personne/Grossesse' => array(
					'DDGRO',
					'DTDECLGRO',
				),
				'/InfoDemandeRSA/Personne/InformationsAgricoles/Benefices' => array(
					'MTBENAGRI',
					'DTBENAGRI',
					'MTBENAGRIA-1',
					'DTBENAGRIA-1',
					'DTCLOEXECOMPTA',
					'REGFISAGRI',
					'TOPRESSEVAAGRI',
				),
				'/InfoDemandeRSA/Personne/InformationsAgricoles/AidesAgricoles' => array(
					'ANNREFAIDEAGRI',
					'LIBNATAIDEAGRI',
					'MTAIDEAGRI',
				),
				'/InfoDemandeRSA/Personne/InformationsETI/ActiviteETI' => array(
					'TOPCREAENTRE',
					'TOPACCRE',
					'ACTETI',
				),
				'/InfoDemandeRSA/Personne/InformationsETI/Employes' => array(
					'TOPEMPL1AX',
					'TOPSTAG1AX',
					'TOPSANSEMPL',
				),
				'/InfoDemandeRSA/Personne/InformationsETI/ChiffreAffaire' => array(
					'DDCHIAFFAETI',
					'DFCHIAFFAETI',
					'MTCHIAFFAETI',
				),
				'/InfoDemandeRSA/Personne/InformationsETI/ElementsFiscaux' => array(
					'REGFISETI',
					'REGFISETIA-1',
					'MTBENETIA-1',
					'MTAMOETI',
					'MTPLUSVALUETI',
					'TOPEVOREVETI',
					'LIBEVOREVETI',
					'TOPRESSEVAETI',
				),
				'/InfoDemandeRSA/Personne/ConditionActivitePrealable/ResultatPeriodeEtudiee' => array(
					'DDCONDACTPREA',
					'DFCONDACTPREA',
					'TOPCONDACTPREA',
					'NBHEUACTTOT',
				),
				'/InfoDemandeRSA/Personne/SuiviAppuiOrientation' => array(
					'TOPOBLSOCPRO',
					'TOPSOUHSOCPRO',
					'SITPERSSOCPRO',
					'DTENRSOCPRO',
					'DTENRPARCO',
					'DTENRORIE',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/GeneraliteDSPP' => array(
					'SITPERSDEMRSA',
					'TOPISOGROOUENF',
					'TOPDRORSARMIANT',
					'DRORSARMIANTA-2',
					'TOPCOUVSOC',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/CommunSituationSociale' => array(
					'ACCOSOCFAM',
					'LIBCOORACCOSOCFAM',
					'ACCOSOCINDI',
					'LIBCOORACCOSOCINDI',
					'SOUTDEMARSOC',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailDifficulteSituationSociale' => array(
					'DIFSOC',
					'LIBAUTRDIFSOC',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailAccompagnementSocialFamilial' => array(
					'NATACCOSOCFAM',
					'LIBAUTRACCOSOCFAM',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailAccompagnementSocialIndividuel' => array(
					'NATACCOSOCINDI',
					'LIBAUTRACCOSOCINDI',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailDifficulteDisponibilite' => array(
					'DIFDISP',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/NiveauEtude' => array(
					'NIVETU',
					'NIVDIPMAXOBT',
					'ANNOBTNIVDIPMAX',
					'TOPQUALIPRO',
					'LIBAUTRQUALIPRO',
					'TOPCOMPEEXTRAPRO',
					'LIBCOMPEEXTRAPRO',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/DisponibiliteEmploi' => array(
					'TOPENGDEMARECHEMPLOI',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/SituationProfessionnelle' => array(
					'HISPRO',
					'LIBDERACT',
					'LIBSECACTDERACT',
					'CESSDERACT',
					'TOPDOMIDERACT',
					'LIBACTDOMI',
					'LIBSECACTDOMI',
					'DURACTDOMI',
					'INSCDEMEMPLOI',
					'TOPISOGRORECHEMPLOI',
					'ACCOEMPLOI',
					'LIBCOORACCOEMPLOI',
					'TOPPROJPRO',
					'LIBEMPLOIRECH',
					'LIBSECACTRECH',
					'TOPCREAREPRIENTRE',
					'CONCOFORMQUALIEMPLOI',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/Mobilite/CommunMobilite' => array(
					'TOPMOYLOCO',
					'TOPPERMICONDUB',
					'TOPAUTRPERMICONDU',
					'LIBAUTRPERMICONDU',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/Mobilite/DetailMobilite' => array(
					'NATMOB',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/DifficulteLogement/CommunDifficulteLogement' => array(
					'NATLOG',
					'DEMARLOG',
				),
				'/InfoDemandeRSA/Personne/DonneesSocioProfessionnelles/DifficulteLogement/DetailDifficulteLogement' => array(
					'DIFLOG',
					'LIBAUTRDIFLOG',
				),
				'/InfoDemandeRSA/Personne/Parcours/DeterminationParcours' => array(
					'NATPARCOCAL',
					'NATPARCOMOD',
					'TOPREFUPARCO',
					'MOTIMODPARCO',
				),
				'/InfoDemandeRSA/Personne/Parcours/OrganismeDecisionOrientation' => array(
					'RAISOCORGDECIORIE',
					'NUMVOIE',
					'COMPLIDEADR',
					'COMPLADR',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'CODEPOS',
					'NOMCOM',
					'NUMTELORGDECIORIE',
					'DTRVORGDECIORIE',
					'HRRVORGDECIORIE',
					'LIBADRRVORGDECIORIE',
					'NUMTELRVORGDECIORIE',
				),
				'/InfoDemandeRSA/Personne/Orientation/OrganismeReferentOrientation' => array(
					'RAISOCORGORIE',
					'NUMVOIE',
					'COMPLIDEADR',
					'COMPLADR',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'CODEPOS',
					'NOMCOM',
					'NUMTELORGORIE',
					'DTRVORGORIE',
					'HRRVORGORIE',
					'LIBADRRVORGORIE',
					'NUMTELRVORGORIE',
				),
				'/InfoDemandeRSA/DonneesAdministratives/SituationFamille' => array(
					'SITFAM',
					'DDSITFAM',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Adresse/TroncCommunAdresse' => array(
					'RGADR',
					'DTEMM',
					'PAYS',
					'TYPEADR',
					'ETATADR',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Adresse/AdresseDetailleeFrance' => array(
					'COMPLIDEADR',
					'COMPLADR',
					'NUMVOIE',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'NUMCOM',
					'CODEPOS',
					'NOMCOM',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Adresse/DonneesComplementairesAdresse' => array(
					'TYPERES',
					'TOPRESETR',
				),
				'/InfoDemandeRSA/DonneesAdministratives/ElectionDomicile' => array(
					'RAISOCTIEELECTDOM',
				),
				'/InfoDemandeRSA/DonneesAdministratives/ModesContacts' => array(
					'NUMTEL',
					'NATTEL',
					'MATETEL',
					'AUTORUTITEL',
					'ADRELEC',
					'AUTORUTIADRELEC',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Logement' => array(
					'TYPEOCCLOG',
					'MTVALLOCTERR',
					'MTVALLOCLOG',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Paiement/Destinataire' => array(
					'TOPVERSTIE',
					'MODEPAI',
					'TOPRIBCONJ',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Paiement/RIB/TitulaireCompte' => array(
					'TITURIB',
					'NOMPRENOMTITURIB',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Paiement/RIB/IBAN' => array(
					'NUMDEBIBAN',
					'ETABAN',
					'GUIBAN',
					'NUMCOMPTBAN',
					'CLERIB',
					'NUMFINIBAN',
				),
				'/InfoDemandeRSA/DonneesAdministratives/Paiement/RIB/IdentiteBanque' => array(
					'COMBAN',
					'BIC',
				),
				'/InfoDemandeRSA/FicheLiaison' => array(
					'CONTEFICHLIAIRSA',
				),
				'/InfoDemandeRSA/PrestationRSA' => array(
					'MTESTRSA',
					'SURFAGRIDOM',
					'DDSURFAGRIDOM',
					'NBTOTAIDEFAMSURFDOM',
					'NBTOTPERSMAJOSURFDOM',
				),
				'/TransmissionFlux' => array(
					'NBTOTDEMRSATRANSM',
				)
			),
			'Recueil DSP VIRD0201 IRSA DSP-v14' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
				),
				'/InfoDemandeRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE',
				),
				'/InfoDemandeRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfoDemandeRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA',
				),
				'/InfoDemandeRSA/IdentificationRSA/SuiviInstruction' => array(
					'SUIIRSA',
					'NOMINS',
					'PRENOMINS',
					'NUMDEPINS',
					'TYPESERINS',
					'NUMCOMINS',
					'NUMAGRINS',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
					'DTNAI',
					'NIR',
					'SEXE',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/Prestations' => array(
					'NATPREST',
					'ROLEPERS',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/SuiviAppuiOrientation' => array(
					'SITPERSSOCPRO',
					'DTENRSOCPRO',
					'DTENRPARCO',
					'DTENRORIE',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/GeneraliteDSPP' => array(
					'SITPERSDEMRSA',
					'TOPISOGROOUENF',
					'TOPDRORSARMIANT',
					'DRORSARMIANTA-2',
					'TOPCOUVSOC',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/CommunSituationSociale' => array(
					'ACCOSOCFAM',
					'LIBCOORACCOSOCFAM',
					'ACCOSOCINDI',
					'LIBCOORACCOSOCINDI',
					'SOUTDEMARSOC',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailDifficulteSituationSociale' => array(
					'DIFSOC',
					'LIBAUTRDIFSOC',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailAccompagnementSocialFamilial' => array(
					'NATACCOSOCFAM',
					'LIBAUTRACCOSOCFAM',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailAccompagnementSocialIndividuel' => array(
					'NATACCOSOCINDI',
					'LIBAUTRACCOSOCINDI',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/SituationSociale/DetailDifficulteDisponibilite' => array(
					'DIFDISP',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/NiveauEtude' => array(
					'NIVETU',
					'NIVDIPMAXOBT',
					'ANNOBTNIVDIPMAX',
					'TOPQUALIPRO',
					'LIBAUTRQUALIPRO',
					'TOPCOMPEEXTRAPRO',
					'LIBCOMPEEXTRAPRO',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/DisponibiliteEmploi' => array(
					'TOPENGDEMARECHEMPLOI',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/SituationProfessionnelle' => array(
					'HISPRO',
					'LIBDERACT',
					'LIBSECACTDERACT',
					'CESSDERACT',
					'TOPDOMIDERACT',
					'LIBACTDOMI',
					'LIBSECACTDOMI',
					'DURACTDOMI',
					'INSCDEMEMPLOI',
					'TOPISOGRORECHEMPLOI',
					'ACCOEMPLOI',
					'LIBCOORACCOEMPLOI',
					'TOPPROJPRO',
					'LIBEMPLOIRECH',
					'LIBSECACTRECH',
					'TOPCREAREPRIENTRE',
					'CONCOFORMQUALIEMPLOI',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/Mobilite/CommunMobilite' => array(
					'TOPMOYLOCO',
					'TOPPERMICONDUB',
					'TOPAUTRPERMICONDU',
					'LIBAUTRPERMICONDU',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/Mobilite/DetailMobilite' => array(
					'NATMOB',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/DifficulteLogement/CommunDifficulteLogement' => array(
					'NATLOG',
					'DEMARLOG',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/DonneesSocioProfessionnelles/DifficulteLogement/DetailDifficulteLogement' => array(
					'DIFLOG',
					'LIBAUTRDIFLOG',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/Parcours/DeterminationParcours' => array(
					'NATPARCOCAL',
					'NATPARCOMOD',
					'TOPREFUPARCO',
					'MOTIMODPARCO',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/Parcours/OrganismeDecisionOrientation' => array(
					'RAISOCORGDECIORIE',
					'NUMVOIE',
					'COMPLIDEADR',
					'COMPLADR',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'CODEPOS',
					'NOMCOM',
					'NUMTELORGDECIORIE',
					'DTRVORGDECIORIE',
					'HRRVORGDECIORIE',
					'LIBADRRVORGDECIORIE',
					'NUMTELRVORGDECIORIE',
				),
				'/InfoDemandeRSA/IdentificationRSA/Personne/Orientation/OrganismeReferentOrientation' => array(
					'RAISOCORGORIE',
					'NUMVOIE',
					'COMPLIDEADR',
					'COMPLADR',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'CODEPOS',
					'NOMCOM',
					'NUMTELORGORIE',
					'DTRVORGORIE',
					'HRRVORGORIE',
					'LIBADRRVORGORIE',
					'NUMTELRVORGORIE',
				),
				'/InfoDemandeRSA/IdentificationRSA/DonneesAdministratives/SituationFamille' => array(
					'SITFAM',
					'DDSITFAM',
				),
				'/InfoDemandeRSA/IdentificationRSA/DonneesAdministratives/Adresse/TroncCommunAdresse' => array(
					'RGADR',
					'DTEMM',
					'PAYS',
					'TYPEADR',
					'ETATADR',
				),
				'/InfoDemandeRSA/IdentificationRSA/DonneesAdministratives/Adresse/AdresseDetailleeFrance' => array(
					'COMPLIDEADR',
					'COMPLADR',
					'NUMVOIE',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'NUMCOM',
					'CODEPOS',
					'NOMCOM',
				),
				'/TransmissionFlux' => array(
					'NBTOTDEMRSATRANSM',
				)
			),
			'Créance VRSC0201-Cristal V42' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
					'DTREF',
				),
				'/InfosCreanceFoyerRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE',
				),
				'/InfosCreanceFoyerRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosCreanceFoyerRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA',
				),
				'/InfosCreanceFoyerRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
					'PRENOM2',
					'PRENOM3',
					'NOMCOMNAI',
					'DTNAI',
					'RGNAI',
					'TYPEDTNAI',
					'NIR',
					'TOPVALIEC',
					'SEXE',
				),
				'/InfosCreanceFoyerRSA/Personne/DossierCAF' => array(
					'TOPRESPDOS',
					'DDRATDOS',
					'DFRATDOS',
				),
				'/InfosCreanceFoyerRSA/DonneesAdministratives/Adresse/TroncCommunAdresse' => array(
					'RGADR',
					'DTEMM',
					'PAYS',
					'TYPEADR',
					'ETATADR',
				),
				'/InfosCreanceFoyerRSA/DonneesAdministratives/Adresse/AdresseDetailleeFrance' => array(
					'COMPLIDEADR',
					'COMPLADR',
					'NUMVOIE',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'NUMCOM',
					'CODEPOS',
					'NOMCOM',
				),
				'/InfosCreanceFoyerRSA/DonneesAdministratives/Adresse/AdresseHorsFrance' => array(
					'LIBLIG2ADR',
					'LIBLIG3ADR',
					'LIBLIG4ADR',
					'LIBLIG5ADR',
					'LIBLIG6ADR',
					'LIBLIG7ADR',
				),
				'/InfosCreanceFoyerRSA/Creance/CreancesTransferees/IdentificationCreance' => array(
					'DTIMPLCRE',
					'NATCRE',
					'RGCRE',
				),
				'/InfosCreanceFoyerRSA/Creance/CreancesTransferees/DetailCreance' => array(
					'MOISMOUCOMPTA',
					'MOTIINDU',
					'ORIINDU',
					'RESPINDU',
					'DDREGUCRE',
					'DFREGUCRE',
					'DTDERCREDCRETRANS',
					'MTSOLREELCRETRANS',
					'MTINICRE',
				),
				'/Anomalie' => array(
					'LIBANO',
				),
				'/TransmissionFlux' => array(
					'NBTOTDOSRSATRANSM',
					'NBTOTDOSRSATRANSMANO',
				)
			),
			'Financier VRSF0501-Cristal V42' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
					'DTREF',
				),
				'/InfosFinancieresFoyerRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE',
				),
				'/InfosFinancieresFoyerRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosFinancieresFoyerRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA',
				),
				'/InfosFinancieresFoyerRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
					'PRENOM2',
					'PRENOM3',
					'NOMCOMNAI',
					'DTNAI',
					'RGNAI',
					'TYPEDTNAI',
					'NIR',
					'TOPVALIEC',
					'SEXE',
				),
				'/InfosFinancieresFoyerRSA/Personne/DossierCAF' => array(
					'TOPRESPDOS',
					'DDRATDOS',
					'DFRATDOS',
				),
				'/InfosFinancieresFoyerRSA/DonneesAdministratives/Adresse/TroncCommunAdresse' => array(
					'RGADR',
					'DTEMM',
					'PAYS',
					'TYPEADR',
					'ETATADR',
				),
				'/InfosFinancieresFoyerRSA/DonneesAdministratives/Adresse/AdresseDetailleeFrance' => array(
					'COMPLIDEADR',
					'COMPLADR',
					'NUMVOIE',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'NUMCOM',
					'CODEPOS',
					'NOMCOM',
				),
				'/InfosFinancieresFoyerRSA/DonneesAdministratives/Adresse/AdresseHorsFrance' => array(
					'LIBLIG2ADR',
					'LIBLIG3ADR',
					'LIBLIG4ADR',
					'LIBLIG5ADR',
					'LIBLIG6ADR',
					'LIBLIG7ADR',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/GeneraliteAcompteRSA' => array(
					'MOISMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/DetailAcompteRSA/AllocationsComptabilisees/DetailAllocationComptabilisée' => array(
					'NATPFCRE',
					'RGCRE',
					'NUMINTMOUCOMPTA',
					'TYPEOPECOMPTA',
					'SENSOPECOMPTA',
					'MTMOUCOMPTA',
					'DDREGU',
					'DTTRAIMOUCOMPTA',
					'HEUTRAIMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/DetailAcompteRSA/IndusConstates/DetailInduConstate' => array(
					'NATPFCRE',
					'RGCRE',
					'NUMINTMOUCOMPTA',
					'TYPEOPECOMPTA',
					'SENSOPECOMPTA',
					'MTMOUCOMPTA',
					'DTTRAIMOUCOMPTA',
					'HEUTRAIMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/DetailAcompteRSA/IndusTransferesCG/DetailnduTransfereCG' => array(
					'NATPFCRE',
					'RGCRE',
					'NUMINTMOUCOMPTA',
					'TYPEOPECOMPTA',
					'SENSOPECOMPTA',
					'MTMOUCOMPTA',
					'DTTRAIMOUCOMPTA',
					'HEUTRAIMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/DetailAcompteRSA/RemisesIndus/DetailRemiseIndu' => array(
					'NATPFCRE',
					'RGCRE',
					'NUMINTMOUCOMPTA',
					'TYPEOPECOMPTA',
					'SENSOPECOMPTA',
					'MTMOUCOMPTA',
					'DTTRAIMOUCOMPTA',
					'HEUTRAIMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/DetailAcompteRSA/AnnulationsFaibleMontant/DetailAnnulationFaibleMontant' => array(
					'NATPFCRE',
					'RGCRE',
					'NUMINTMOUCOMPTA',
					'TYPEOPECOMPTA',
					'SENSOPECOMPTA',
					'MTMOUCOMPTA',
					'DTTRAIMOUCOMPTA',
					'HEUTRAIMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/AcompteRSA/DetailAcompteRSA/AutresAnnulations/DetailAutreAnnulation' => array(
					'NATPFCRE',
					'RGCRE',
					'NUMINTMOUCOMPTA',
					'TYPEOPECOMPTA',
					'SENSOPECOMPTA',
					'MTMOUCOMPTA',
					'DTTRAIMOUCOMPTA',
					'HEUTRAIMOUCOMPTA',
				),
				'/InfosFinancieresFoyerRSA/Anomalie' => array(
					'LIBANO',
				),
				'/TotalisationAcompte/TotalAllocationsComptabilisees' => array(
					'MTTOTSOCLRSA',
					'MTTOTSOCLMAJORSA',
					'MTTOTLOCALRSA',
					'MTTOTRSA',
				),
				'/TotalisationAcompte/TotalIndusConstates' => array(
					'MTTOTSOCLRSA',
					'MTTOTSOCLMAJORSA',
					'MTTOTLOCALRSA',
					'MTTOTRSA',
				),
				'/TotalisationAcompte/TotalIndusTransferésCG' => array(
					'MTTOTSOCLRSA',
					'MTTOTSOCLMAJORSA',
					'MTTOTLOCALRSA',
					'MTTOTRSA',
				),
				'/TotalisationAcompte/TotalRemisesIndus' => array(
					'MTTOTSOCLRSA',
					'MTTOTSOCLMAJORSA',
					'MTTOTLOCALRSA',
					'MTTOTRSA',
				),
				'/TotalisationAcompte/TotalAnnulationsIndus' => array(
					'MTTOTSOCLRSA',
					'MTTOTSOCLMAJORSA',
					'MTTOTLOCALRSA',
					'MTTOTRSA',
				),
				'/TotalisationAcompte/MontantTotalAcompte' => array(
					'MTTOTSOCLRSA',
					'MTTOTSOCLMAJORSA',
					'MTTOTLOCALRSA',
					'MTTOTRSA',
				),
				'/TransmissionFlux' => array(
					'NBTOTDOSRSATRANSM',
					'NBTOTDOSRSATRANSMANO',
				)
			),
			// FIXME: prendre la version 0301
			// cf. vrsd-refonte flux beneficaires 2015-10-14.xls
			'Bénéficiaire VRSD0301' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'VERSIONFLUX',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
					'DTREF',
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosFoyerRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE',
				),
				'/InfosFoyerRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosFoyerRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA',
					'ORIDEMRSA',
					'DTORIDEMRSA',
				),
				'/InfosFoyerRSA/IdentificationRSA/OrganismeCedant' => array(
					'FONORGCEDMUT',
					'NUMORGCEDMUT',
					'MATRICULEORGCEDMUT',
					'DDARRMUT',
				),
				'/InfosFoyerRSA/IdentificationRSA/OrganismePrenant' => array(
					'FONORGPRENMUT',
					'NUMORGPRENMUT',
					'DDDEPAMUT',
				),
				'/InfosFoyerRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
					'LISPRENOMS',
					'LIEUNAI',
					'LOCANAI',
					'PAYSNAI',
					'DTNAI',
					'RGNAI',
					'TYPEDTNAI',
					'NIR',
					'TOPVALIEC',
					'SEXE',
					'DTDC',
				),
				'/InfosFoyerRSA/Personne/DossierCafMsa' => array(
					'TOPRESPDOS',
					'DFRATDOS',
				),
				'/InfosFoyerRSA/Personne/FonctionPersonnePFA' => array(
					'ROLEPERS',
				),
				'/InfosFoyerRSA/Personne/FonctionPersonneRSA' => array(
					'ROLEPERS',
					'TOPCHAPERS',
				),
				'/InfosFoyerRSA/Personne/Rattachement' => array(
					'NIR',
					'TYPEPAR',
				),
				'/InfosFoyerRSA/Personne/Ressources/GeneraliteRessourcesTrimestre' => array(
					'TOPRESSNUL',
				),
				'/InfosFoyerRSA/Personne/Ressources/RessourcesMensuelles/GeneraliteRessourcesMensuelles' => array(
					'MOISRESS',
				),
				'/InfosFoyerRSA/Personne/Ressources/RessourcesMensuelles/DetailRessourcesMensuelles' => array(
					'NATRESS',
					'MTNATRESSMEN',
					'ABANEU',
				),
				'/InfosFoyerRSA/Personne/CaracteristiquesEmployabilite' => array(
					'REG',
					'STATUEMPL',
					'TOPPERSMALHAN',
					'DDSTATUEMPL',
					'DFSTATUEMPL',
				),
				'/InfosFoyerRSA/Personne/Grossesse' => array(
					'DDGRO',
					'DTDECLGRO',
				),
				'/InfosFoyerRSA/Personne/MesureProtection/IdentificationMesureProtection' => array(
					'FONORG',
					'NUMORG',
					'NUMPERSMESUPROT',
					'TYPEPERSMESUPROT',
				),
				'/InfosFoyerRSA/Personne/MesureProtection/MesureProtectionCommun' => array(
					'TYPEMESUPROT',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ConditionNonSalarie' => array(
					'AVISEVARESSNONSAL',
					'TOPCONDADMNONSAL',
					'DTSOURESSNONSAL',
					'DTEVARESSNONSAL',
					'MTEVARESSNONSAL',
					'COMMPROPRESSEVA',
					'DDRESSNONSALEVA',
					'DFRESSNONSALEVA',
					'MTRESSNONSALEVA',
					'RESSNONSALEVA',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ConditionExploitantAgricole' => array(
					'MTBENAGRI',
					'REGFISAGRI',
					'DTBENAGRI',
					'MTREVAGRI',
					'TYPEXPAGRI',
					'NATACTEXPAGRI',
					'PARTEXPAGRI',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/Derogation' => array(
					'TYPEDERO',
					'AVISDERO',
					'DDAVISDERO',
					'DFAVISDERO',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ExclueRSA' => array(
					'EXCL',
					'DDEXCL',
					'DFEXCL',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/Liberalite' => array(
					'MTLIBERNONDECL',
					'DTABSDECLLIBER',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/CreanceAlimentaire' => array(
					'ETATCREALIM',
					'DDCREALIM',
					'MTSANCREALIM',
				),
				'/InfosFoyerRSA/Personne/AvisCGSSDOMPersonne' => array(
					'JUSACTDOM',
					'RESUJUSACTDOM',
				),
				'/InfosFoyerRSA/Personne/ContratPCGPersonneRSA' => array(
					'DDCONTRRSA',
					'DFCONTRRSA',
					'TYPECONTRRSA',
				),
				'/InfosFoyerRSA/Personne/CalculDroitRSAPersonne' => array(
					'TOPPERSDRODEVORSA',
					'TOPPERSENTDRODEVORSA',
					'DDSOUDRODEV',
					'DFSOUDRODEV',
					'DTDERCALRSA',
					'MTPERSRESSMENRSA',
					'MTPERSABANEURSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/SituationFamille' => array(
					'SITFAM',
					'DDSITFAM',
					'REGAGRIFAM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse/TroncCommunAdresse' => array(
					'RGADR',
					'DTEMM',
					'PAYS',
					'TYPEADR',
					'ETATADR',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse/AdresseDetailleeFrance' => array(
					'COMPLIDEADR',
					'COMPLADR',
					'NUMVOIE',
					'LIBTYPEVOIE',
					'NOMVOIE',
					'LIEUDIST',
					'NUMCOM',
					'CODEPOS',
					'NOMCOM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse/AdresseHorsFrance' => array(
					'LIBLIG2ADR',
					'LIBLIG3ADR',
					'LIBLIG4ADR',
					'LIBLIG5ADR',
					'LIBLIG6ADR',
					'LIBLIG7ADR',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/EtatDossierRSA' => array(
					'ETATDOSRSA',
					'TOPFORCDRO',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/DroitOuvert' => array(
					'DTODRSA',
					'MOTIODRSA',
					'TOPMAINTDRORSA',
					'TOPMTINFSEUIRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/SuspensionDroit' => array(
					'MOTISUSDRORSA',
					'DDSUSDRORSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/RessourcesTropElevees' => array(
					'MOTISUSVERSRSA',
					'DDSUSVERSRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/SituationDossierRSA/FinDroit' => array(
					'MOTICLORSA',
					'DTCLORSA',
					'TOPANNUOD',
				),
				'/InfosFoyerRSA/PrestationRSA/SpecificiteDOM' => array(
					'SURFAGRIDOM',
					'DDSURFAGRIDOM',
					'SURFAGRIDOMPLA',
					'NBTOTAIDEFAMSURFDOM',
					'NBTOTPERSMAJOSURFDOM',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/TroncCommunDroitRSA' => array(
					'TOPSANSDOMFIXE',
					'DDRESS',
					'DFRESS',
					'MTRSAVERS',
					'DTDERRSAVERS',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/MontantsCalculDroitRSA' => array(
					'DDELECAL',
					'DFELECAL',
					'NBENFAUTCHA',
					'MTREVMINIGARARSA',
					'MTPENTRSA',
					'MTLOCALRSA',
					'MTREVGARARSA',
					'MTPFRSA',
					'MTALRSA',
					'MTRESSMENRSA',
					'MTSANADMRSA',
					'MTREDADMRSA',
					'MTSANCGRSA ',
					'MTCUMINTEGRSA',
					'MTABANEURSA',
					'MTBRUTRSA',
					'MTTOTDRORSA',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSASocle' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'DTINIRSASOCL',
					'MTBRUTRSASOCL',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSAActivite' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'DTINIRSAACT',
					'MTBRUTRSAACT',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSASocle-1' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'MTBRUTRSASOCL',
				),
				'/InfosFoyerRSA/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSAActivite-1' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'MTBRUTRSAACT',
				),
				'/InfosFoyerRSA/PrestationRSA/AvisPCGDroitRSA/ConditionAdministrative' => array(
					'AVISCONDADMRSA',
					'MOTICONDADMRSA',
					'COMM1CONDADMRSA',
					'COMM2CONDADMRSA',
					'DTEFFAVISCONDADMRSA',
				),
				'/InfosFoyerRSA/PrestationRSA/AvisPCGDroitRSA/PaiementTiers' => array(
					'AVISDESTPAIRSA',
					'DTAVISDESTPAIRSA',
					'NOMTIE',
					'TYPEPERSTIE',
				),
				'/InfosFoyerRSA/Evenement/SessionEvenement' => array(
					'DTLIQ',
					'HEULIQ',
					'DDEFFLIQ',
					'DFEFFLIQ',
				),
				'/InfosFoyerRSA/Evenement/ListeMotifsEvenement' => array(
					'MOTITRANSFLUX',
				),
				'/InfosFoyerRSA/Anomalie' => array(
					'LIBANO',
				),
				'/TransmissionFlux' => array(
					'NBTOTDOSRSATRANSM',
					'NBCARATRANSM',
					'NBTOTDOSRSATRANSMANO',
				),
			),
			// cf. 1-VRSD0101_Refonte_flux_BeneficiaireV1.1.xls
			'Bénéficiaire VRSD0101' => array(
				'/IdentificationFlux' => array(
					'APPLIEME',
					'NUMVERSIONAPPLIEME',
					'VERSIONFLUX',
					'TYPEFLUX',
					'NATFLUX',
					'DTCREAFLUX',
					'HEUCREAFLUX',
					'DTREF',
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosFoyerRSA/IdentificationRSA/Organisme' => array(
					'FONORG',
					'NUMORG',
					'MATRICULE',
				),
				'/InfosFoyerRSA/IdentificationRSA/Partenaire' => array(
					'TYPEPARTE',
					'IDEPARTE',
				),
				'/InfosFoyerRSA/IdentificationRSA/DemandeRSA' => array(
					'DTDEMRSA',
					'NUMDEMRSA',
					'ORIDEMRSA',
					'DTORIDEMRSA',
				),
				'/InfosFoyerRSA/IdentificationRSA/OrganismeCedant' => array(
					'FONORGCEDMUT',
					'NUMORGCEDMUT',
					'MATRICULEORGCEDMUT',
					'DDARRMUT',
				),
				'/InfosFoyerRSA/IdentificationRSA/OrganismePrenant' => array(
					'FONORGPRENMUT',
					'NUMORGPRENMUT',
					'DDDEPAMUT',
				),
				'/InfosFoyerRSA/Personne/Identification' => array(
					'QUAL',
					'NOM',
					'NOMNAI',
					'PRENOM',
				),
				'/InfosFoyerRSA/Personne/Identification' => array(
					'LISPRENOMS',
					'LIEUNAI',
					'LOCANAI',
					'PAYSNAI',
					'DTNAI',
					'RGNAI',
					'TYPEDTNAI',
					'NIR',
					'TOPVALIEC',
					'SEXE',
					'DTDC',
				),
				'/InfosFoyerRSA/Personne/DossierCafMsa' => array(
					'TOPRESPDOS',
					'DDRATDOS',
					'DFRATDOS',
				),
				'/InfosFoyerRSA/Personne/FonctionPersonnePFA' => array(
					'ROLEPERS',
				),
				'/InfosFoyerRSA/Personne/FonctionPersonneRSA' => array(
					'ROLEPERS',
					'TOPCHAPERS',
				),
				'/InfosFoyerRSA/Personne/Rattachement' => array(
					'NIR',
					'TYPEPAR',
				),
				'/InfosFoyerRSA/Personne/Ressources/GeneraliteRessourcesTrimestre' => array(
					'TOPRESSNUL',
					'DDRESS',
					'DFRESS',
				),
				'/InfosFoyerRSA/Personne/Ressources/RessourcesMensuelles/GeneraliteRessourcesMensuelles' => array(
					'MOISRESS',
				),
				'/InfosFoyerRSA/Personne/Ressources/RessourcesMensuelles/DetailRessourcesMensuelles' => array(
					'NATRESS',
					'MTNATRESSMEN',
					'ABANEU',
				),
				'/InfosFoyerRSA/Personne/Ressources/CaracteristiquesEmployabilite' => array(
					'REG',
					'STATUEMPL',
					'TOPPERSMALHAN',
					'DDSTATUEMPL',
					'DFSTATUEMPL',
				),
				'/InfosFoyerRSA/Personne/Grossesse' => array(
					'DDGRO',
					'DFGRO',
					'DTDECLGRO',
					'NATFINGRO',
				),
				'/InfosFoyerRSA/Personne/MesureProtection/IdentificationMesureProtection' => array(
					'FONORG',
					'NUMORG',
					'NUMPERSMESUPROT',
					'TYPEPERSMESUPROT',
				),
				'/InfosFoyerRSA/Personne/MesureProtection/MesureProtectionCommun' => array(
					'TYPEMESUPROT',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ConditionNonSalarie' => array(
					'AVISEVARESSNONSAL',
					'TOPCONDADMNONSAL',
					'DTSOURESSNONSAL',
					'DTEVARESSNONSAL',
					'MTEVARESSNONSAL',
					'COMMPROPRESSEVA',
					'DDRESSNONSALEVA',
					'DFRESSNONSALEVA',
					'MTRESSNONSALEVA',
					'RESSNONSALEVA',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ConditionExploitantAgricole' => array(
					'MTBENAGRI',
					'REGFISAGRI',
					'DTBENAGRI',
					'MTREVAGRI',
					'TYPEXPAGRI',
					'NATACTEXPAGRI',
					'PARTEXPAGRI',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/Dérogation' => array(
					'TYPEDERO',
					'AVISDERO',
					'DDAVISDERO',
					'DFAVISDERO',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/ExclueRSA' => array(
					'EXCL',
					'DDEXCL',
					'DFEXCL',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/Liberalite' => array(
					'MTLIBERNONDECL',
					'DTABSDECLLIBER',
				),
				'/InfosFoyerRSA/Personne/AvisPCGPersonne/CreanceAlimentaire' => array(
					'ETATCREALIM',
					'DDCREALIM',
					'DFCREALIM',
					'ORIOBLALIM',
					'MOTIDISCREALIM',
					'COMMCREALIM',
					'MTSANCREALIM',
				),
				'/InfosFoyerRSA/Personne/AvisCGSSDOMPersonne' => array(
					'JUSACTDOM',
					'RESUJUSACTDOM',
				),
				'/InfosFoyerRSA/Personne/ContratPCGPersonneRSA' => array(
					'DDCONTRRSA',
					'DFCONTRRSA',
					'TYPECONTRRSA',
				),
				'/InfosFoyerRSA/Personne/SanctionPCGPersonneRSA/DecisionSanctionPCGPersonneRSA' => array(
					'DDSANRSA',
					'DFSANRSA',
					'NIVSANRSA',
					'TXSANRSA',
					'MTSANRSADEM',
					'MOTISANRSA',
				),
				'/InfosFoyerRSA/Personne/SanctionPCGPersonneRSA/ApplicationSanctionPCGPersonneRSA' => array(
					'DTREFSANRSA',
					'MTREFSANRSA',
					'REFCOMPOSFOYSANRSA',
					'MTSANRSAAVTPLA',
					'MTSANRSAAPPL',
				),
				'/InfosFoyerRSA/Personne/SanctionPCGPersonneRSA/LeveeSanctionPCGPersonneRSA' => array(
					'DTLEVSANRSA',
					'MOTILEVSANRSA',
				),
				'/InfosFoyerRSA/Personne/FraudePCGPersonneRSA' => array(
					'DDSUSRSAFRAU',
					'DFSUSRSAFRAU',
				),
				'/InfosFoyerRSA/Personne/CalculDroitRSAPersonne' => array(
					'TOPPERSDRODEVORSA',
					'TOPPERSENTDRODEVORSA',
					'DDSOUDRODEV',
					'DFSOUDRODEV',
					'DTDERCALRSA',
					'MTPERSRESSMENRSA',
					'MTPERSABANEURSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/SituationFamille' => array(
					'SITFAM',
					'DDSITFAM',
					'REGAGRIFAM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/Adresse' => array(
					'RGADR',
					'DTEMM',
					'NUMVOIE',
					'TYPEVOIE',
					'NOMVOIE',
					'COMPLIDEADR',
					'COMPLADR',
					'LIEUDIST',
					'NUMCOM',
					'CODEPOS',
					'LOCAADR',
					'PAYS',
					'TYPEADR',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/EtatDossierRSA' => array(
					'ETATDOSRSA',
					'TOPFORCDRO',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/EnAttente' => array(
					'DTATTEDEMRSA',
					'MOTIATTEDEMRSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/Refus' => array(
					'DTREFURSA',
					'MOTIREFURSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/DroitOuvert' => array(
					'DTODRSA',
					'MOTIODRSA',
					'TOPMAINTDRORSA',
					'TOPMTINFSEUIRSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/SuspensionDroit' => array(
					'MOTISUSDRORSA',
					'DDSUSDRORSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/RessourcesTropElevees' => array(
					'MOTISUSVERSRSA',
					'DDSUSVERSRSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SituationDossierRSA/FinDroit' => array(
					'MOTICLORSA',
					'DTCLORSA',
					'TOPANNUOD',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/SpecificiteDOM' => array(
					'SURFAGRIDOM',
					'DDSURFAGRIDOM',
					'SURFAGRIDOMPLA',
					'NBTOTAIDEFAMSURFDOM',
					'NBTOTPERSMAJOSURFDOM',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/DetailDroitRSA/MontantsCalculDroitRSA' => array(
					'DDELECAL',
					'DFELECAL',
					'NBENFAUTCHA',
					'MTREVMINIGARARSA',
					'MTPENTRSA',
					'MTLOCALRSA',
					'MTREVGARARSA',
					'MTPFRSA',
					'MTALRSA',
					'MTRESSMENRSA',
					'MTSANADMRSA',
					'MTREDADMRSA',
					'MTSANCGRSA',
					'MTCUMINTEGRSA',
					'MTABANEURSA',
					'MTBRUTRSA',
					'MTTOTDRORSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSASocle' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'DTINIRSASOCL',
					'MTBRUTRSASOCL',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSAActivite' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'DTINIRSAACT',
					'MTBRUTRSAACT',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSASocle-1' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'MTBRUTRSASOCL',
				),
				'/InfosFoyerRSA/DonneesAdministratives/PrestationRSA/DetailDroitRSA/DetailCalculDroitRSA/RSAActivite-1' => array(
					'NATPF',
					'SOUSNATPF',
					'DDNATDRO',
					'DFNATDRO',
					'MTBRUTRSAACT',
				),
				'/InfosFoyerRSA/DonneesAdministratives/AvisPCGDroitRSA/ConditionAdministrative' => array(
					'AVISCONDADMRSA',
					'MOTICONDADMRSA',
					'COMM1CONDADMRSA',
					'COMM2CONDADMRSA',
					'DTEFFAVISCONDADMRSA',
				),
				'/InfosFoyerRSA/DonneesAdministratives/AvisPCGDroitRSA/PaiementTiers' => array(
					'AVISDESTPAIRSA',
					'DTAVISDESTPAIRSA',
					'NOMTIE',
					'TYPEPERSTIE',
				),
				'/InfosFoyerRSA/Evenement/SessionEvenement' => array(
					'DTLIQ',
					'HEULIQ',
					'DDEFFLIQ',
					'DFEFFLIQ',
				),
				'/InfosFoyerRSA/Evenement/ListeMotifsEvenement' => array(
					'MOTITRANSFLUX',
				),
				'/InfosFoyerRSA/Anomalie' => array(
					'LIBANO',
				),
				'/InfosFoyerRSA/Anomalie' => array(
					'LIBANO',
				),
				'/TransmissionFlux' => array(
					'NBTOTDOSRSATRANSM',
					'NBCARATRANSM',
					'NBTOTDOSRSATRANSMANO',
				),
			)
		);
	}
?>